#pragma once
#include <QHash>
#include <QString>

// Rich emoji keyword dataset (English + Persian فارسی)
// Each emoji maps to space-separated searchable keywords
inline QHash<QString, QString> buildKeywordMap() {
    return {
    // ===== Smileys & People =====
    {QString::fromUtf8("😀"), QString::fromUtf8("grinning smile happy face grin خنده لبخند خوشحال")},
    {QString::fromUtf8("😃"), QString::fromUtf8("smiley happy open mouth خنده شاد")},
    {QString::fromUtf8("😄"), QString::fromUtf8("smile happy grin eyes خنده چشم")},
    {QString::fromUtf8("😁"), QString::fromUtf8("beaming grin happy teeth خنده دندان")},
    {QString::fromUtf8("😆"), QString::fromUtf8("laughing laugh happy squint خنده بلند")},
    {QString::fromUtf8("😅"), QString::fromUtf8("sweat smile nervous awkward عرق خنده")},
    {QString::fromUtf8("😂"), QString::fromUtf8("joy tears laugh crying funny خنده اشک شوق خنده‌دار")},
    {QString::fromUtf8("🤣"), QString::fromUtf8("rofl rolling floor laugh خنده غلتیدن")},
    {QString::fromUtf8("🥲"), QString::fromUtf8("smile tear happy sad bittersweet لبخند اشک")},
    {QString::fromUtf8("☺️"), QString::fromUtf8("relaxed blush smile happy آرام لبخند")},
    {QString::fromUtf8("😊"), QString::fromUtf8("blush smile happy shy خجالتی لبخند")},
    {QString::fromUtf8("😇"), QString::fromUtf8("angel innocent halo smile فرشته معصوم")},
    {QString::fromUtf8("🙂"), QString::fromUtf8("slight smile okay fine لبخند کم")},
    {QString::fromUtf8("🙃"), QString::fromUtf8("upside down silly sarcasm وارونه")},
    {QString::fromUtf8("😉"), QString::fromUtf8("wink flirt playful چشمک")},
    {QString::fromUtf8("😌"), QString::fromUtf8("relieved peaceful calm آرام آسوده")},
    {QString::fromUtf8("😍"), QString::fromUtf8("heart eyes love crush adore عاشق قلب چشم دوست")},
    {QString::fromUtf8("🥰"), QString::fromUtf8("love hearts smile affection عشق محبت دوست")},
    {QString::fromUtf8("😘"), QString::fromUtf8("kiss blow kiss love heart بوسه عشق")},
    {QString::fromUtf8("😗"), QString::fromUtf8("kiss kissing بوس بوسه")},
    {QString::fromUtf8("😙"), QString::fromUtf8("kiss smile happy بوسه لبخند")},
    {QString::fromUtf8("😚"), QString::fromUtf8("kiss blush love بوس خجالت")},
    {QString::fromUtf8("😋"), QString::fromUtf8("yummy delicious tongue tasty food خوشمزه لذیذ زبان غذا")},
    {QString::fromUtf8("😛"), QString::fromUtf8("tongue playful silly زبان شیطون")},
    {QString::fromUtf8("😝"), QString::fromUtf8("tongue squint silly playful زبان")},
    {QString::fromUtf8("😜"), QString::fromUtf8("wink tongue crazy playful چشمک زبان دیوانه")},
    {QString::fromUtf8("🤪"), QString::fromUtf8("zany crazy wild silly دیوانه وحشی")},
    {QString::fromUtf8("🤨"), QString::fromUtf8("raised eyebrow suspicious doubt مشکوک ابرو")},
    {QString::fromUtf8("🧐"), QString::fromUtf8("monocle curious inspect think فکر بررسی کنجکاو")},
    {QString::fromUtf8("🤓"), QString::fromUtf8("nerd glasses smart geek عینکی باهوش")},
    {QString::fromUtf8("😎"), QString::fromUtf8("cool sunglasses awesome باحال عینک آفتابی")},
    {QString::fromUtf8("🥸"), QString::fromUtf8("disguise glasses mustache تغییر قیافه سبیل")},
    {QString::fromUtf8("🤩"), QString::fromUtf8("star struck amazing wow excited ذوق‌زده ستاره هیجان")},
    {QString::fromUtf8("🥳"), QString::fromUtf8("party celebrate birthday horn جشن تولد مهمانی")},
    {QString::fromUtf8("😏"), QString::fromUtf8("smirk suggestive sly پوزخند موذی")},
    {QString::fromUtf8("😒"), QString::fromUtf8("unamused annoyed bored ناراحت کسل بی‌حوصله")},
    {QString::fromUtf8("😞"), QString::fromUtf8("disappointed sad unhappy ناامید ناراحت غمگین")},
    {QString::fromUtf8("😔"), QString::fromUtf8("pensive sad thoughtful غمگین متفکر")},
    {QString::fromUtf8("😟"), QString::fromUtf8("worried nervous concern نگران مضطرب")},
    {QString::fromUtf8("😕"), QString::fromUtf8("confused puzzled unsure گیج سردرگم")},
    {QString::fromUtf8("🙁"), QString::fromUtf8("frown sad unhappy ناراحت غمگین")},
    {QString::fromUtf8("☹️"), QString::fromUtf8("frown sad unhappy ناراحت")},
    {QString::fromUtf8("😣"), QString::fromUtf8("persevere struggle suffering تلاش سختی")},
    {QString::fromUtf8("😖"), QString::fromUtf8("confounded frustrated stressed ناامید")},
    {QString::fromUtf8("😫"), QString::fromUtf8("tired weary exhausted خسته کلافه")},
    {QString::fromUtf8("😩"), QString::fromUtf8("weary tired sad exhausted خسته ناراحت")},
    {QString::fromUtf8("🥺"), QString::fromUtf8("pleading puppy eyes please بغض التماس خواهش")},
    {QString::fromUtf8("😢"), QString::fromUtf8("cry tear sad گریه اشک غمگین")},
    {QString::fromUtf8("😭"), QString::fromUtf8("sob crying loud tears گریه زار اشک")},
    {QString::fromUtf8("😤"), QString::fromUtf8("angry steam huff frustrated عصبانی خشمگین")},
    {QString::fromUtf8("😠"), QString::fromUtf8("angry mad furious عصبانی خشمگین")},
    {QString::fromUtf8("😡"), QString::fromUtf8("rage angry red furious خشمگین عصبانی قرمز")},
    {QString::fromUtf8("🤬"), QString::fromUtf8("swearing curse angry symbols فحش بد عصبانی")},
    {QString::fromUtf8("🤯"), QString::fromUtf8("exploding head mind blown shocked ذهن منفجر شوکه")},
    {QString::fromUtf8("😳"), QString::fromUtf8("flushed embarrassed surprised shocked شرمنده شوکه تعجب")},
    {QString::fromUtf8("🥵"), QString::fromUtf8("hot warm sweating heat گرم داغ عرق")},
    {QString::fromUtf8("🥶"), QString::fromUtf8("cold freezing frozen ice سرد یخ زده")},
    {QString::fromUtf8("😱"), QString::fromUtf8("scream horror fear shocked ترس وحشت جیغ")},
    {QString::fromUtf8("😨"), QString::fromUtf8("fearful scared afraid ترسیده وحشت‌زده")},
    {QString::fromUtf8("😰"), QString::fromUtf8("anxious worried sweat نگران مضطرب عرق")},
    {QString::fromUtf8("😥"), QString::fromUtf8("sad relieved disappointed sweat ناراحت")},
    {QString::fromUtf8("😓"), QString::fromUtf8("downcast sweat tired خسته عرق")},
    {QString::fromUtf8("🤗"), QString::fromUtf8("hug hugging warm embrace بغل آغوش گرم")},
    {QString::fromUtf8("🤔"), QString::fromUtf8("thinking think hmm wonder فکر فکرکردن تفکر")},
    {QString::fromUtf8("🤭"), QString::fromUtf8("giggle oops cover mouth خنده ریز دست دهان")},
    {QString::fromUtf8("🤫"), QString::fromUtf8("shush quiet secret silence هیس ساکت سکوت راز")},
    {QString::fromUtf8("🤥"), QString::fromUtf8("lying liar pinocchio nose دروغ دروغگو")},
    {QString::fromUtf8("😶"), QString::fromUtf8("mute silent no mouth ساکت بی‌صدا")},
    {QString::fromUtf8("😐"), QString::fromUtf8("neutral expressionless blank بی‌تفاوت")},
    {QString::fromUtf8("😑"), QString::fromUtf8("expressionless blank بی‌حالت")},
    {QString::fromUtf8("😬"), QString::fromUtf8("grimace awkward teeth ناراحت")},
    {QString::fromUtf8("🙄"), QString::fromUtf8("eye roll annoyed whatever چشم چرخاندن")},
    {QString::fromUtf8("😯"), QString::fromUtf8("hushed surprised quiet تعجب ساکت")},
    {QString::fromUtf8("😦"), QString::fromUtf8("frown open mouth surprise تعجب")},
    {QString::fromUtf8("😧"), QString::fromUtf8("anguish worried surprised نگران")},
    {QString::fromUtf8("😮"), QString::fromUtf8("open mouth wow surprise واو تعجب")},
    {QString::fromUtf8("😲"), QString::fromUtf8("astonished amazed shocked شگفت‌زده متعجب")},
    {QString::fromUtf8("🥱"), QString::fromUtf8("yawn bored tired sleepy خمیازه خسته خواب‌آلود")},
    {QString::fromUtf8("😴"), QString::fromUtf8("sleep sleeping zzz snore خواب خوابیده")},
    {QString::fromUtf8("🤤"), QString::fromUtf8("drool drooling hungry آب دهان گرسنه")},
    {QString::fromUtf8("😪"), QString::fromUtf8("sleepy tired bubble خواب‌آلود خسته")},
    {QString::fromUtf8("😵"), QString::fromUtf8("dizzy drunk spiral knocked گیج منگ")},
    {QString::fromUtf8("🤐"), QString::fromUtf8("zipper mouth shut secret zip دهان بسته زیپ")},
    {QString::fromUtf8("🥴"), QString::fromUtf8("woozy drunk tipsy dizzy مست گیج")},
    {QString::fromUtf8("🤢"), QString::fromUtf8("nauseated sick green حالت تهوع مریض")},
    {QString::fromUtf8("🤮"), QString::fromUtf8("vomit puke sick throw up استفراغ مریض")},
    {QString::fromUtf8("🤧"), QString::fromUtf8("sneeze tissue cold sick عطسه سرماخوردگی")},
    {QString::fromUtf8("😷"), QString::fromUtf8("mask sick doctor medical ماسک بیمار دکتر")},
    {QString::fromUtf8("🤒"), QString::fromUtf8("thermometer fever sick ill تب بیمار")},
    {QString::fromUtf8("🤕"), QString::fromUtf8("bandage hurt injured head زخمی باند سر")},
    {QString::fromUtf8("🤑"), QString::fromUtf8("money rich dollar greed پول ثروتمند دلار")},
    {QString::fromUtf8("🤠"), QString::fromUtf8("cowboy hat western country کابوی کلاه")},
    {QString::fromUtf8("😈"), QString::fromUtf8("devil evil smile horns شیطان بدجنس")},
    {QString::fromUtf8("👿"), QString::fromUtf8("devil angry evil imp شیطان عصبانی")},
    {QString::fromUtf8("👹"), QString::fromUtf8("ogre monster demon scary هیولا ترسناک")},
    {QString::fromUtf8("👺"), QString::fromUtf8("goblin tengu mask ماسک")},
    {QString::fromUtf8("🤡"), QString::fromUtf8("clown circus funny joke دلقک سیرک")},
    {QString::fromUtf8("💩"), QString::fromUtf8("poop poo shit funny مدفوع")},
    {QString::fromUtf8("👻"), QString::fromUtf8("ghost boo spooky halloween روح شبح جن")},
    {QString::fromUtf8("💀"), QString::fromUtf8("skull dead death skeleton جمجمه مرگ اسکلت")},
    {QString::fromUtf8("👽"), QString::fromUtf8("alien ufo space extraterrestrial آدم فضایی بیگانه")},
    {QString::fromUtf8("👾"), QString::fromUtf8("alien monster game space invader بازی هیولا")},
    {QString::fromUtf8("🤖"), QString::fromUtf8("robot bot machine ربات ماشین")},

    // ===== Animals & Nature =====
    {QString::fromUtf8("🐶"), QString::fromUtf8("dog puppy pet cute سگ توله حیوان خانگی")},
    {QString::fromUtf8("🐱"), QString::fromUtf8("cat kitten pet meow گربه بچه‌گربه")},
    {QString::fromUtf8("🐭"), QString::fromUtf8("mouse rat موش")},
    {QString::fromUtf8("🐹"), QString::fromUtf8("hamster pet cute همستر")},
    {QString::fromUtf8("🐰"), QString::fromUtf8("rabbit bunny cute خرگوش")},
    {QString::fromUtf8("🦊"), QString::fromUtf8("fox clever foxy روباه")},
    {QString::fromUtf8("🐻"), QString::fromUtf8("bear grizzly brown خرس")},
    {QString::fromUtf8("🐼"), QString::fromUtf8("panda bear cute پاندا خرس")},
    {QString::fromUtf8("🐻‍❄️"), QString::fromUtf8("polar bear white arctic ice خرس قطبی سفید")},
    {QString::fromUtf8("🐨"), QString::fromUtf8("koala bear australia کوالا")},
    {QString::fromUtf8("🐯"), QString::fromUtf8("tiger cat wild ببر")},
    {QString::fromUtf8("🦁"), QString::fromUtf8("lion king wild jungle شیر سلطان جنگل")},
    {QString::fromUtf8("🐮"), QString::fromUtf8("cow cattle گاو")},
    {QString::fromUtf8("🐷"), QString::fromUtf8("pig piggy خوک")},
    {QString::fromUtf8("🐽"), QString::fromUtf8("pig nose snout بینی خوک")},
    {QString::fromUtf8("🐸"), QString::fromUtf8("frog toad green قورباغه سبز")},
    {QString::fromUtf8("🐵"), QString::fromUtf8("monkey face میمون")},
    {QString::fromUtf8("🙈"), QString::fromUtf8("see no evil monkey shy میمون نبین خجالت")},
    {QString::fromUtf8("🙉"), QString::fromUtf8("hear no evil monkey میمون نشنو")},
    {QString::fromUtf8("🙊"), QString::fromUtf8("speak no evil monkey میمون نگو")},
    {QString::fromUtf8("🐒"), QString::fromUtf8("monkey animal میمون حیوان")},
    {QString::fromUtf8("🐔"), QString::fromUtf8("chicken hen bird مرغ پرنده")},
    {QString::fromUtf8("🐧"), QString::fromUtf8("penguin bird cold ice پنگوئن")},
    {QString::fromUtf8("🐦"), QString::fromUtf8("bird tweet fly پرنده")},
    {QString::fromUtf8("🐤"), QString::fromUtf8("chick baby bird جوجه")},
    {QString::fromUtf8("🐣"), QString::fromUtf8("hatching chick egg baby جوجه تخم‌مرغ")},
    {QString::fromUtf8("🐥"), QString::fromUtf8("chick baby front جوجه")},
    {QString::fromUtf8("🦆"), QString::fromUtf8("duck bird water اردک")},
    {QString::fromUtf8("🦅"), QString::fromUtf8("eagle bird prey عقاب")},
    {QString::fromUtf8("🦉"), QString::fromUtf8("owl bird night wise جغد شب")},
    {QString::fromUtf8("🦇"), QString::fromUtf8("bat vampire night خفاش شب")},
    {QString::fromUtf8("🐺"), QString::fromUtf8("wolf howl wild گرگ")},
    {QString::fromUtf8("🐗"), QString::fromUtf8("boar pig wild گراز")},
    {QString::fromUtf8("🐴"), QString::fromUtf8("horse pony اسب")},
    {QString::fromUtf8("🦄"), QString::fromUtf8("unicorn magic fantasy تک‌شاخ اسب شاخدار")},
    {QString::fromUtf8("🐝"), QString::fromUtf8("bee honey buzz sting زنبور عسل")},
    {QString::fromUtf8("🪱"), QString::fromUtf8("worm soil کرم")},
    {QString::fromUtf8("🐛"), QString::fromUtf8("bug caterpillar insect کرم حشره")},
    {QString::fromUtf8("🦋"), QString::fromUtf8("butterfly insect beautiful پروانه")},
    {QString::fromUtf8("🐌"), QString::fromUtf8("snail slow shell حلزون آهسته")},
    {QString::fromUtf8("🐞"), QString::fromUtf8("ladybug beetle insect red کفشدوزک")},
    {QString::fromUtf8("🐜"), QString::fromUtf8("ant insect small مورچه حشره")},
    {QString::fromUtf8("🪰"), QString::fromUtf8("fly insect buzz مگس")},
    {QString::fromUtf8("🪲"), QString::fromUtf8("beetle bug insect سوسک")},
    {QString::fromUtf8("🪳"), QString::fromUtf8("cockroach bug roach سوسک")},
    {QString::fromUtf8("🦟"), QString::fromUtf8("mosquito insect bite پشه")},
    {QString::fromUtf8("🦗"), QString::fromUtf8("cricket insect chirp جیرجیرک")},
    {QString::fromUtf8("🕷"), QString::fromUtf8("spider web creepy عنکبوت تار")},
    {QString::fromUtf8("🕸"), QString::fromUtf8("spider web cobweb تار عنکبوت")},
    {QString::fromUtf8("🦂"), QString::fromUtf8("scorpion sting عقرب نیش")},
    {QString::fromUtf8("🐢"), QString::fromUtf8("turtle tortoise slow shell لاک‌پشت آهسته")},
    {QString::fromUtf8("🐍"), QString::fromUtf8("snake serpent مار")},
    {QString::fromUtf8("🦎"), QString::fromUtf8("lizard reptile مارمولک")},
    {QString::fromUtf8("🦖"), QString::fromUtf8("dinosaur trex دایناسور")},
    {QString::fromUtf8("🦕"), QString::fromUtf8("dinosaur sauropod brontosaurus دایناسور")},
    {QString::fromUtf8("🐙"), QString::fromUtf8("octopus sea tentacle اختاپوس")},
    {QString::fromUtf8("🦑"), QString::fromUtf8("squid sea ocean ماهی مرکب")},
    {QString::fromUtf8("🦐"), QString::fromUtf8("shrimp prawn seafood میگو")},
    {QString::fromUtf8("🦞"), QString::fromUtf8("lobster seafood خرچنگ")},
    {QString::fromUtf8("🦀"), QString::fromUtf8("crab sea خرچنگ")},
    {QString::fromUtf8("🐡"), QString::fromUtf8("blowfish puffer fish بادکنک‌ماهی")},
    {QString::fromUtf8("🐠"), QString::fromUtf8("tropical fish ماهی")},
    {QString::fromUtf8("🐟"), QString::fromUtf8("fish sea ocean ماهی دریا")},
    {QString::fromUtf8("🐬"), QString::fromUtf8("dolphin sea ocean smart دلفین")},
    {QString::fromUtf8("🐳"), QString::fromUtf8("whale sea ocean spout نهنگ")},
    {QString::fromUtf8("🐋"), QString::fromUtf8("whale ocean sea نهنگ اقیانوس")},
    {QString::fromUtf8("🦈"), QString::fromUtf8("shark danger sea ocean کوسه")},
    {QString::fromUtf8("🦭"), QString::fromUtf8("seal sea فک دریایی")},
    {QString::fromUtf8("🐊"), QString::fromUtf8("crocodile alligator تمساح")},
    {QString::fromUtf8("🐅"), QString::fromUtf8("tiger wild cat ببر")},
    {QString::fromUtf8("🐆"), QString::fromUtf8("leopard cheetah wild پلنگ یوزپلنگ")},
    {QString::fromUtf8("🦓"), QString::fromUtf8("zebra stripes گورخر")},
    {QString::fromUtf8("🦍"), QString::fromUtf8("gorilla ape strong گوریل")},
    {QString::fromUtf8("🦧"), QString::fromUtf8("orangutan ape اورانگوتان")},
    {QString::fromUtf8("🦣"), QString::fromUtf8("mammoth woolly extinct ماموت")},
    {QString::fromUtf8("🐘"), QString::fromUtf8("elephant big trunk فیل")},
    {QString::fromUtf8("🦛"), QString::fromUtf8("hippo hippopotamus اسب آبی")},
    {QString::fromUtf8("🦏"), QString::fromUtf8("rhino rhinoceros horn کرگدن")},
    {QString::fromUtf8("🐪"), QString::fromUtf8("camel desert one hump شتر بیابان")},
    {QString::fromUtf8("🐫"), QString::fromUtf8("camel desert two humps شتر دوکوهانه")},
    {QString::fromUtf8("🦒"), QString::fromUtf8("giraffe tall spots زرافه")},
    {QString::fromUtf8("🦘"), QString::fromUtf8("kangaroo australia jump کانگورو")},
    {QString::fromUtf8("🦬"), QString::fromUtf8("bison buffalo گاومیش")},
    {QString::fromUtf8("🐃"), QString::fromUtf8("water buffalo گاومیش")},
    {QString::fromUtf8("🐂"), QString::fromUtf8("ox bull گاو نر")},
    {QString::fromUtf8("🐄"), QString::fromUtf8("cow dairy milk گاو شیری")},
    {QString::fromUtf8("🐎"), QString::fromUtf8("horse racing fast اسب مسابقه")},
    {QString::fromUtf8("🐖"), QString::fromUtf8("pig pork خوک")},
    {QString::fromUtf8("🐏"), QString::fromUtf8("ram sheep horn قوچ")},
    {QString::fromUtf8("🐑"), QString::fromUtf8("sheep lamb wool گوسفند بره پشم")},
    {QString::fromUtf8("🦙"), QString::fromUtf8("llama alpaca لاما")},
    {QString::fromUtf8("🐐"), QString::fromUtf8("goat بز")},
    {QString::fromUtf8("🦌"), QString::fromUtf8("deer stag antler گوزن آهو")},
    {QString::fromUtf8("🐕"), QString::fromUtf8("dog pet سگ")},
    {QString::fromUtf8("🐩"), QString::fromUtf8("poodle dog fancy پودل سگ")},
    {QString::fromUtf8("🦮"), QString::fromUtf8("guide dog service سگ راهنما")},
    {QString::fromUtf8("🐕‍🦺"), QString::fromUtf8("service dog vest سگ خدماتی")},
    {QString::fromUtf8("🐈"), QString::fromUtf8("cat pet گربه")},
    {QString::fromUtf8("🐈‍⬛"), QString::fromUtf8("black cat گربه سیاه")},
    {QString::fromUtf8("🪶"), QString::fromUtf8("feather bird quill پر")},
    {QString::fromUtf8("🐓"), QString::fromUtf8("rooster chicken cock خروس")},
    {QString::fromUtf8("🦃"), QString::fromUtf8("turkey bird بوقلمون")},
    {QString::fromUtf8("🦤"), QString::fromUtf8("dodo bird extinct دودو")},
    {QString::fromUtf8("🦚"), QString::fromUtf8("peacock bird feather طاووس")},
    {QString::fromUtf8("🦜"), QString::fromUtf8("parrot bird colorful طوطی")},
    {QString::fromUtf8("🦢"), QString::fromUtf8("swan bird elegant white قو")},
    {QString::fromUtf8("🦩"), QString::fromUtf8("flamingo bird pink فلامینگو")},
    {QString::fromUtf8("🕊"), QString::fromUtf8("dove peace bird white کبوتر صلح")},
    {QString::fromUtf8("🐇"), QString::fromUtf8("rabbit bunny خرگوش")},
    {QString::fromUtf8("🦝"), QString::fromUtf8("raccoon راکون")},
    {QString::fromUtf8("🦨"), QString::fromUtf8("skunk smell اسکانک")},
    {QString::fromUtf8("🦡"), QString::fromUtf8("badger گورکن")},
    {QString::fromUtf8("🦫"), QString::fromUtf8("beaver dam سگ آبی")},
    {QString::fromUtf8("🦦"), QString::fromUtf8("otter sea cute سمور")},
    {QString::fromUtf8("🦥"), QString::fromUtf8("sloth slow lazy تنبل")},
    {QString::fromUtf8("🐁"), QString::fromUtf8("mouse small موش کوچک")},
    {QString::fromUtf8("🐀"), QString::fromUtf8("rat rodent موش صحرایی")},
    {QString::fromUtf8("🐿"), QString::fromUtf8("squirrel chipmunk nut سنجاب")},
    {QString::fromUtf8("🦔"), QString::fromUtf8("hedgehog spikes جوجه‌تیغی")},

    // ===== Food & Drink =====
    {QString::fromUtf8("🍏"), QString::fromUtf8("green apple fruit سیب سبز میوه")},
    {QString::fromUtf8("🍎"), QString::fromUtf8("red apple fruit سیب قرمز میوه")},
    {QString::fromUtf8("🍐"), QString::fromUtf8("pear fruit گلابی میوه")},
    {QString::fromUtf8("🍊"), QString::fromUtf8("orange tangerine fruit پرتقال نارنگی")},
    {QString::fromUtf8("🍋"), QString::fromUtf8("lemon citrus sour لیمو ترش")},
    {QString::fromUtf8("🍌"), QString::fromUtf8("banana fruit yellow موز")},
    {QString::fromUtf8("🍉"), QString::fromUtf8("watermelon fruit summer هندوانه تابستان")},
    {QString::fromUtf8("🍇"), QString::fromUtf8("grapes fruit wine انگور")},
    {QString::fromUtf8("🍓"), QString::fromUtf8("strawberry fruit red توت‌فرنگی")},
    {QString::fromUtf8("🫐"), QString::fromUtf8("blueberry fruit بلوبری")},
    {QString::fromUtf8("🍈"), QString::fromUtf8("melon fruit طالبی")},
    {QString::fromUtf8("🍒"), QString::fromUtf8("cherry fruit red گیلاس")},
    {QString::fromUtf8("🍑"), QString::fromUtf8("peach fruit هلو")},
    {QString::fromUtf8("🥭"), QString::fromUtf8("mango fruit tropical انبه")},
    {QString::fromUtf8("🍍"), QString::fromUtf8("pineapple fruit tropical آناناس")},
    {QString::fromUtf8("🥥"), QString::fromUtf8("coconut tropical نارگیل")},
    {QString::fromUtf8("🥝"), QString::fromUtf8("kiwi fruit green کیوی")},
    {QString::fromUtf8("🍅"), QString::fromUtf8("tomato red vegetable گوجه")},
    {QString::fromUtf8("🍆"), QString::fromUtf8("eggplant aubergine purple بادمجان")},
    {QString::fromUtf8("🥑"), QString::fromUtf8("avocado fruit green آووکادو")},
    {QString::fromUtf8("🥦"), QString::fromUtf8("broccoli vegetable green کلم بروکلی")},
    {QString::fromUtf8("🥬"), QString::fromUtf8("leafy green lettuce vegetable کاهو سبزی")},
    {QString::fromUtf8("🥒"), QString::fromUtf8("cucumber vegetable green خیار")},
    {QString::fromUtf8("🌶"), QString::fromUtf8("hot pepper chili spicy فلفل تند")},
    {QString::fromUtf8("🫑"), QString::fromUtf8("bell pepper vegetable فلفل دلمه")},
    {QString::fromUtf8("🌽"), QString::fromUtf8("corn maize ذرت")},
    {QString::fromUtf8("🥕"), QString::fromUtf8("carrot vegetable orange هویج")},
    {QString::fromUtf8("🫒"), QString::fromUtf8("olive oil زیتون")},
    {QString::fromUtf8("🧄"), QString::fromUtf8("garlic cooking سیر")},
    {QString::fromUtf8("🧅"), QString::fromUtf8("onion cooking پیاز")},
    {QString::fromUtf8("🥔"), QString::fromUtf8("potato vegetable سیب‌زمینی")},
    {QString::fromUtf8("🍠"), QString::fromUtf8("sweet potato yam سیب‌زمینی شیرین")},
    {QString::fromUtf8("🥐"), QString::fromUtf8("croissant bread french pastry کروسان نان")},
    {QString::fromUtf8("🥯"), QString::fromUtf8("bagel bread بیگل نان")},
    {QString::fromUtf8("🍞"), QString::fromUtf8("bread loaf toast نان")},
    {QString::fromUtf8("🥖"), QString::fromUtf8("baguette french bread نان فرانسوی")},
    {QString::fromUtf8("🥨"), QString::fromUtf8("pretzel snack bread پرتزل")},
    {QString::fromUtf8("🧀"), QString::fromUtf8("cheese dairy yellow پنیر")},
    {QString::fromUtf8("🥚"), QString::fromUtf8("egg breakfast تخم‌مرغ")},
    {QString::fromUtf8("🍳"), QString::fromUtf8("fried egg cooking breakfast تخم‌مرغ نیمرو صبحانه")},
    {QString::fromUtf8("🧈"), QString::fromUtf8("butter dairy کره")},
    {QString::fromUtf8("🥞"), QString::fromUtf8("pancake breakfast پنکیک صبحانه")},
    {QString::fromUtf8("🧇"), QString::fromUtf8("waffle breakfast وافل")},
    {QString::fromUtf8("🥓"), QString::fromUtf8("bacon meat breakfast بیکن گوشت")},
    {QString::fromUtf8("🥩"), QString::fromUtf8("meat steak beef cut گوشت استیک")},
    {QString::fromUtf8("🍗"), QString::fromUtf8("chicken leg drumstick ران مرغ")},
    {QString::fromUtf8("🍖"), QString::fromUtf8("meat bone rib گوشت استخوان")},
    {QString::fromUtf8("🦴"), QString::fromUtf8("bone dog استخوان")},
    {QString::fromUtf8("🌭"), QString::fromUtf8("hotdog sausage هات‌داگ سوسیس")},
    {QString::fromUtf8("🍔"), QString::fromUtf8("hamburger burger fast food همبرگر برگر فست فود")},
    {QString::fromUtf8("🍟"), QString::fromUtf8("fries french fries fast food سیب‌زمینی سرخ‌شده")},
    {QString::fromUtf8("🍕"), QString::fromUtf8("pizza slice italian پیتزا ایتالیایی")},
    {QString::fromUtf8("🫓"), QString::fromUtf8("flatbread naan نان")},
    {QString::fromUtf8("🥪"), QString::fromUtf8("sandwich lunch ساندویچ")},
    {QString::fromUtf8("🥙"), QString::fromUtf8("pita falafel wrap فلافل")},
    {QString::fromUtf8("🧆"), QString::fromUtf8("falafel vegetarian فلافل")},
    {QString::fromUtf8("🌮"), QString::fromUtf8("taco mexican food تاکو مکزیکی")},
    {QString::fromUtf8("🌯"), QString::fromUtf8("burrito wrap mexican بوریتو")},
    {QString::fromUtf8("🫔"), QString::fromUtf8("tamale mexican food تامالی")},
    {QString::fromUtf8("🥗"), QString::fromUtf8("salad healthy green vegetable سالاد سبزیجات")},
    {QString::fromUtf8("🥘"), QString::fromUtf8("stew pot cooking خورشت قابلمه")},
    {QString::fromUtf8("🫕"), QString::fromUtf8("fondue cheese فوندو پنیر")},
    {QString::fromUtf8("🥫"), QString::fromUtf8("canned food tin کنسرو")},
    {QString::fromUtf8("🍝"), QString::fromUtf8("spaghetti pasta italian اسپاگتی پاستا ماکارونی")},
    {QString::fromUtf8("🍜"), QString::fromUtf8("noodle ramen soup نودل رامن سوپ")},
    {QString::fromUtf8("🍲"), QString::fromUtf8("pot stew soup food آبگوشت سوپ")},
    {QString::fromUtf8("🍛"), QString::fromUtf8("curry rice indian کاری برنج")},
    {QString::fromUtf8("🍣"), QString::fromUtf8("sushi japanese fish سوشی ژاپنی")},
    {QString::fromUtf8("🍱"), QString::fromUtf8("bento box lunch japanese بنتو ژاپنی")},
    {QString::fromUtf8("🥟"), QString::fromUtf8("dumpling chinese dim sum دامپلینگ")},
    {QString::fromUtf8("🦪"), QString::fromUtf8("oyster shell sea صدف")},
    {QString::fromUtf8("🍤"), QString::fromUtf8("shrimp prawn fried میگو سرخ‌شده")},
    {QString::fromUtf8("🍙"), QString::fromUtf8("rice ball onigiri japanese برنج")},
    {QString::fromUtf8("🍚"), QString::fromUtf8("rice cooked white برنج")},
    {QString::fromUtf8("🍘"), QString::fromUtf8("rice cracker snack بیسکویت برنجی")},
    {QString::fromUtf8("🍥"), QString::fromUtf8("fish cake narutomaki ناروتو")},
    {QString::fromUtf8("🥠"), QString::fromUtf8("fortune cookie بیسکویت")},
    {QString::fromUtf8("🥮"), QString::fromUtf8("mooncake cake کیک")},
    {QString::fromUtf8("🍢"), QString::fromUtf8("oden skewer سیخ")},
    {QString::fromUtf8("🍡"), QString::fromUtf8("dango sweet japanese دانگو")},
    {QString::fromUtf8("🍧"), QString::fromUtf8("shaved ice dessert cold بستنی یخی")},
    {QString::fromUtf8("🍨"), QString::fromUtf8("ice cream dessert sweet بستنی دسر")},
    {QString::fromUtf8("🍦"), QString::fromUtf8("ice cream cone soft serve بستنی قیفی")},
    {QString::fromUtf8("🥧"), QString::fromUtf8("pie dessert baked پای")},
    {QString::fromUtf8("🧁"), QString::fromUtf8("cupcake cake sweet dessert کاپ‌کیک")},
    {QString::fromUtf8("🍰"), QString::fromUtf8("cake slice birthday dessert sweet کیک دسر شیرینی")},
    {QString::fromUtf8("🎂"), QString::fromUtf8("birthday cake candle celebration کیک تولد شمع جشن")},
    {QString::fromUtf8("🍮"), QString::fromUtf8("custard pudding flan دسر پودینگ")},
    {QString::fromUtf8("🍭"), QString::fromUtf8("lollipop candy sweet آبنبات شیرینی")},
    {QString::fromUtf8("🍬"), QString::fromUtf8("candy sweet wrapper شکلات آبنبات")},
    {QString::fromUtf8("🍫"), QString::fromUtf8("chocolate bar sweet شکلات")},
    {QString::fromUtf8("🍿"), QString::fromUtf8("popcorn movie snack پاپ‌کورن ذرت‌بوداده سینما")},
    {QString::fromUtf8("🍩"), QString::fromUtf8("donut doughnut sweet دونات")},
    {QString::fromUtf8("🍪"), QString::fromUtf8("cookie biscuit sweet کلوچه بیسکویت")},
    {QString::fromUtf8("🌰"), QString::fromUtf8("chestnut nut بلوط")},
    {QString::fromUtf8("🥜"), QString::fromUtf8("peanut nut بادام‌زمینی")},
    {QString::fromUtf8("🍯"), QString::fromUtf8("honey pot sweet bee عسل")},
    {QString::fromUtf8("🥛"), QString::fromUtf8("milk glass drink شیر لیوان")},
    {QString::fromUtf8("🍼"), QString::fromUtf8("baby bottle milk شیشه شیر نوزاد")},
    {QString::fromUtf8("🫖"), QString::fromUtf8("teapot tea قوری چای")},
    {QString::fromUtf8("☕️"), QString::fromUtf8("coffee hot drink cup قهوه نوشیدنی فنجان چای")},
    {QString::fromUtf8("🍵"), QString::fromUtf8("tea green matcha cup چای سبز فنجان")},
    {QString::fromUtf8("🧃"), QString::fromUtf8("juice box drink آبمیوه")},
    {QString::fromUtf8("🥤"), QString::fromUtf8("cup straw soda drink لیوان نی نوشابه")},
    {QString::fromUtf8("🧋"), QString::fromUtf8("bubble tea boba drink چای حبابی")},
    {QString::fromUtf8("🍶"), QString::fromUtf8("sake japanese rice wine ساکه")},
    {QString::fromUtf8("🍺"), QString::fromUtf8("beer mug drink آبجو")},
    {QString::fromUtf8("🍻"), QString::fromUtf8("beer cheers clink toast آبجو سلامتی")},
    {QString::fromUtf8("🥂"), QString::fromUtf8("champagne cheers toast celebrate سلامتی جشن شامپاین")},
    {QString::fromUtf8("🍷"), QString::fromUtf8("wine glass red drink شراب")},
    {QString::fromUtf8("🥃"), QString::fromUtf8("whisky tumbler drink ویسکی")},
    {QString::fromUtf8("🍸"), QString::fromUtf8("cocktail martini drink کوکتل")},
    {QString::fromUtf8("🍹"), QString::fromUtf8("tropical drink cocktail نوشیدنی")},
    {QString::fromUtf8("🧉"), QString::fromUtf8("mate drink tea نوشیدنی")},
    {QString::fromUtf8("🍾"), QString::fromUtf8("champagne bottle celebrate party شامپاین جشن")},
    {QString::fromUtf8("🧊"), QString::fromUtf8("ice cube cold یخ")},
    {QString::fromUtf8("🥄"), QString::fromUtf8("spoon utensil قاشق")},
    {QString::fromUtf8("🍴"), QString::fromUtf8("fork knife utensil cutlery چنگال کارد")},
    {QString::fromUtf8("🍽"), QString::fromUtf8("plate fork knife dinner بشقاب")},
    {QString::fromUtf8("🥣"), QString::fromUtf8("bowl spoon cereal soup کاسه")},
    {QString::fromUtf8("🥡"), QString::fromUtf8("takeout box food جعبه غذا")},
    {QString::fromUtf8("🥢"), QString::fromUtf8("chopsticks asian food چوب غذاخوری")},
    {QString::fromUtf8("🧂"), QString::fromUtf8("salt shaker seasoning نمک")},

    // ===== Activity =====
    {QString::fromUtf8("⚽️"), QString::fromUtf8("soccer football ball sport فوتبال توپ ورزش")},
    {QString::fromUtf8("🏀"), QString::fromUtf8("basketball ball sport بسکتبال توپ")},
    {QString::fromUtf8("🏈"), QString::fromUtf8("football american sport فوتبال آمریکایی")},
    {QString::fromUtf8("⚾️"), QString::fromUtf8("baseball ball sport بیسبال")},
    {QString::fromUtf8("🥎"), QString::fromUtf8("softball ball sport سافتبال")},
    {QString::fromUtf8("🎾"), QString::fromUtf8("tennis ball racket sport تنیس")},
    {QString::fromUtf8("🏐"), QString::fromUtf8("volleyball ball sport والیبال")},
    {QString::fromUtf8("🏉"), QString::fromUtf8("rugby ball sport راگبی")},
    {QString::fromUtf8("🥏"), QString::fromUtf8("flying disc frisbee فریزبی")},
    {QString::fromUtf8("🎱"), QString::fromUtf8("pool billiard eight ball بیلیارد")},
    {QString::fromUtf8("🪀"), QString::fromUtf8("yoyo toy یویو")},
    {QString::fromUtf8("🏓"), QString::fromUtf8("ping pong table tennis پینگ‌پنگ تنیس")},
    {QString::fromUtf8("🏸"), QString::fromUtf8("badminton shuttlecock بدمینتون")},
    {QString::fromUtf8("🏒"), QString::fromUtf8("ice hockey stick puck هاکی")},
    {QString::fromUtf8("🏑"), QString::fromUtf8("field hockey هاکی")},
    {QString::fromUtf8("🥍"), QString::fromUtf8("lacrosse لاکراس")},
    {QString::fromUtf8("🏏"), QString::fromUtf8("cricket bat ball کریکت")},
    {QString::fromUtf8("🪃"), QString::fromUtf8("boomerang throw بومرنگ")},
    {QString::fromUtf8("🥅"), QString::fromUtf8("goal net دروازه تور")},
    {QString::fromUtf8("⛳️"), QString::fromUtf8("golf flag hole گلف")},
    {QString::fromUtf8("🪁"), QString::fromUtf8("kite flying wind بادبادک")},
    {QString::fromUtf8("🏹"), QString::fromUtf8("bow arrow archery تیر کمان")},
    {QString::fromUtf8("🎣"), QString::fromUtf8("fishing rod ماهیگیری")},
    {QString::fromUtf8("🤿"), QString::fromUtf8("diving mask scuba snorkel غواصی ماسک")},
    {QString::fromUtf8("🥊"), QString::fromUtf8("boxing glove fight punch بوکس مبارزه مشت")},
    {QString::fromUtf8("🥋"), QString::fromUtf8("martial arts karate judo کاراته جودو رزمی")},
    {QString::fromUtf8("🎽"), QString::fromUtf8("running shirt sport ورزش دو")},
    {QString::fromUtf8("🛹"), QString::fromUtf8("skateboard skate اسکیت‌بورد")},
    {QString::fromUtf8("🛼"), QString::fromUtf8("roller skate اسکیت")},
    {QString::fromUtf8("🛷"), QString::fromUtf8("sled sledge snow سورتمه برف")},
    {QString::fromUtf8("⛸"), QString::fromUtf8("ice skate اسکیت یخ")},
    {QString::fromUtf8("🥌"), QString::fromUtf8("curling stone کرلینگ")},
    {QString::fromUtf8("🎿"), QString::fromUtf8("ski skiing snow اسکی برف")},
    {QString::fromUtf8("⛷"), QString::fromUtf8("skier skiing snow اسکی‌باز")},
    {QString::fromUtf8("🏂"), QString::fromUtf8("snowboard snowboarding snow اسنوبورد")},
    {QString::fromUtf8("🪂"), QString::fromUtf8("parachute skydive چتر نجات")},
    {QString::fromUtf8("🏆"), QString::fromUtf8("trophy winner champion gold cup جام قهرمانی برنده طلا")},
    {QString::fromUtf8("🥇"), QString::fromUtf8("gold medal first winner مدال طلا اول برنده")},
    {QString::fromUtf8("🥈"), QString::fromUtf8("silver medal second مدال نقره دوم")},
    {QString::fromUtf8("🥉"), QString::fromUtf8("bronze medal third مدال برنز سوم")},
    {QString::fromUtf8("🏅"), QString::fromUtf8("medal sports مدال ورزشی")},
    {QString::fromUtf8("🎖"), QString::fromUtf8("military medal honor مدال نظامی افتخار")},
    {QString::fromUtf8("🏵"), QString::fromUtf8("rosette flower نشان")},
    {QString::fromUtf8("🎗"), QString::fromUtf8("ribbon reminder روبان یادبود")},
    {QString::fromUtf8("🎫"), QString::fromUtf8("ticket event بلیت")},
    {QString::fromUtf8("🎟"), QString::fromUtf8("admission ticket بلیت ورودی")},
    {QString::fromUtf8("🎪"), QString::fromUtf8("circus tent show سیرک چادر")},
    {QString::fromUtf8("🎭"), QString::fromUtf8("theater drama mask performing arts تئاتر نمایش ماسک")},
    {QString::fromUtf8("🩰"), QString::fromUtf8("ballet shoes dance رقص باله")},
    {QString::fromUtf8("🎨"), QString::fromUtf8("art paint palette color نقاشی هنر رنگ پالت")},
    {QString::fromUtf8("🎬"), QString::fromUtf8("movie clapper film cinema فیلم سینما")},
    {QString::fromUtf8("🎤"), QString::fromUtf8("microphone sing karaoke voice میکروفون آواز خوانندگی")},
    {QString::fromUtf8("🎧"), QString::fromUtf8("headphone music listen audio هدفون موسیقی")},
    {QString::fromUtf8("🎼"), QString::fromUtf8("music score notes نت موسیقی")},
    {QString::fromUtf8("🎹"), QString::fromUtf8("piano keyboard music instrument پیانو کیبورد ساز")},
    {QString::fromUtf8("🥁"), QString::fromUtf8("drum beat percussion طبل درام")},
    {QString::fromUtf8("🪘"), QString::fromUtf8("long drum percussion طبل")},
    {QString::fromUtf8("🎷"), QString::fromUtf8("saxophone sax jazz music ساکسیفون جاز")},
    {QString::fromUtf8("🎺"), QString::fromUtf8("trumpet horn music شیپور ترومپت")},
    {QString::fromUtf8("🪗"), QString::fromUtf8("accordion music آکاردئون")},
    {QString::fromUtf8("🎸"), QString::fromUtf8("guitar rock music electric گیتار راک موسیقی")},
    {QString::fromUtf8("🪕"), QString::fromUtf8("banjo music بنجو")},
    {QString::fromUtf8("🎻"), QString::fromUtf8("violin fiddle music classical ویولن کلاسیک")},
    {QString::fromUtf8("🎲"), QString::fromUtf8("dice game luck chance تاس بازی شانس")},
    {QString::fromUtf8("♟"), QString::fromUtf8("chess piece pawn شطرنج مهره")},
    {QString::fromUtf8("🎯"), QString::fromUtf8("target bullseye dart هدف دارت")},
    {QString::fromUtf8("🎳"), QString::fromUtf8("bowling ball pin بولینگ")},
    {QString::fromUtf8("🎮"), QString::fromUtf8("game controller video play بازی کنترلر گیم")},
    {QString::fromUtf8("🎰"), QString::fromUtf8("slot machine casino gamble اسلات کازینو قمار")},
    {QString::fromUtf8("🧩"), QString::fromUtf8("puzzle piece jigsaw پازل")},
    };
}
