#pragma once
#include <QHash>
#include <QString>

// Rich emoji keyword dataset (English + Persian فارسی)
// Each emoji maps to space-separated searchable keywords
inline QHash<QString, QString> buildKeywordMap() {
    return {
    // ===== Smileys & People =====
    {QString::fromUtf8("😀"), QString::fromUtf8("grinning smile happy face grin خنده لبخند خوشحال")},
    {QString::fromUtf8("😃"), QString::fromUtf8("smiley happy open mouth خنده شاد")},
    {QString::fromUtf8("😄"), QString::fromUtf8("smile happy grin eyes خنده چشم")},
    {QString::fromUtf8("😁"), QString::fromUtf8("beaming grin happy teeth خنده دندان")},
    {QString::fromUtf8("😆"), QString::fromUtf8("laughing laugh happy squint خنده بلند")},
    {QString::fromUtf8("😅"), QString::fromUtf8("sweat smile nervous awkward عرق خنده")},
    {QString::fromUtf8("😂"), QString::fromUtf8("joy tears laugh crying funny خنده اشک شوق خنده‌دار")},
    {QString::fromUtf8("🤣"), QString::fromUtf8("rofl rolling floor laugh خنده غلتیدن")},
    {QString::fromUtf8("🥲"), QString::fromUtf8("smile tear happy sad bittersweet لبخند اشک")},
    {QString::fromUtf8("☺️"), QString::fromUtf8("relaxed blush smile happy آرام لبخند")},
    {QString::fromUtf8("😊"), QString::fromUtf8("blush smile happy shy خجالتی لبخند")},
    {QString::fromUtf8("😇"), QString::fromUtf8("angel innocent halo smile فرشته معصوم")},
    {QString::fromUtf8("🙂"), QString::fromUtf8("slight smile okay fine لبخند کم")},
    {QString::fromUtf8("🙃"), QString::fromUtf8("upside down silly sarcasm وارونه چپه")},
    {QString::fromUtf8("😉"), QString::fromUtf8("wink flirt playful چشمک")},
    {QString::fromUtf8("😌"), QString::fromUtf8("relieved peaceful calm آرام آسوده")},
    {QString::fromUtf8("😍"), QString::fromUtf8("heart eyes love crush adore عاشق قلب چشم دوست")},
    {QString::fromUtf8("🥰"), QString::fromUtf8("love hearts smile affection عشق محبت دوست")},
    {QString::fromUtf8("😘"), QString::fromUtf8("kiss blow kiss love heart بوسه عشق")},
    {QString::fromUtf8("😗"), QString::fromUtf8("kiss kissing بوس بوسه")},
    {QString::fromUtf8("😙"), QString::fromUtf8("kiss smile happy بوسه لبخند")},
    {QString::fromUtf8("😚"), QString::fromUtf8("kiss blush love بوس خجالت")},
    {QString::fromUtf8("😋"), QString::fromUtf8("yummy delicious tongue tasty food خوشمزه لذیذ زبان غذا")},
    {QString::fromUtf8("😛"), QString::fromUtf8("tongue playful silly زبان شیطون")},
    {QString::fromUtf8("😝"), QString::fromUtf8("tongue squint silly playful زبان")},
    {QString::fromUtf8("😜"), QString::fromUtf8("wink tongue crazy playful چشمک زبان دیوانه")},
    {QString::fromUtf8("🤪"), QString::fromUtf8("zany crazy wild silly دیوانه وحشی")},
    {QString::fromUtf8("🤨"), QString::fromUtf8("raised eyebrow suspicious doubt مشکوک ابرو")},
    {QString::fromUtf8("🧐"), QString::fromUtf8("monocle curious inspect think فکر بررسی کنجکاو")},
    {QString::fromUtf8("🤓"), QString::fromUtf8("nerd glasses smart geek عینکی باهوش")},
    {QString::fromUtf8("😎"), QString::fromUtf8("cool sunglasses awesome باحال عینک آفتابی")},
    {QString::fromUtf8("🥸"), QString::fromUtf8("disguise glasses mustache تغییر قیافه سبیل")},
    {QString::fromUtf8("🤩"), QString::fromUtf8("star struck amazing wow excited ذوق‌زده ستاره هیجان")},
    {QString::fromUtf8("🥳"), QString::fromUtf8("party celebrate birthday horn جشن تولد مهمانی")},
    {QString::fromUtf8("😏"), QString::fromUtf8("smirk suggestive sly پوزخند موذی")},
    {QString::fromUtf8("😒"), QString::fromUtf8("unamused annoyed bored ناراحت کسل بی‌حوصله")},
    {QString::fromUtf8("😞"), QString::fromUtf8("disappointed sad unhappy ناامید ناراحت غمگین")},
    {QString::fromUtf8("😔"), QString::fromUtf8("pensive sad thoughtful غمگین متفکر")},
    {QString::fromUtf8("😟"), QString::fromUtf8("worried nervous concern نگران مضطرب")},
    {QString::fromUtf8("😕"), QString::fromUtf8("confused puzzled unsure گیج سردرگم")},
    {QString::fromUtf8("🙁"), QString::fromUtf8("frown sad unhappy ناراحت غمگین")},
    {QString::fromUtf8("☹️"), QString::fromUtf8("frown sad unhappy ناراحت")},
    {QString::fromUtf8("😣"), QString::fromUtf8("persevere struggle suffering تلاش سختی")},
    {QString::fromUtf8("😖"), QString::fromUtf8("confounded frustrated stressed ناامید")},
    {QString::fromUtf8("😫"), QString::fromUtf8("tired weary exhausted خسته کلافه")},
    {QString::fromUtf8("😩"), QString::fromUtf8("weary tired sad exhausted خسته ناراحت")},
    {QString::fromUtf8("🥺"), QString::fromUtf8("pleading puppy eyes please بغض التماس خواهش")},
    {QString::fromUtf8("😢"), QString::fromUtf8("cry tear sad گریه اشک غمگین")},
    {QString::fromUtf8("😭"), QString::fromUtf8("sob crying loud tears گریه زار اشک")},
    {QString::fromUtf8("😤"), QString::fromUtf8("angry steam huff frustrated عصبانی خشمگین")},
    {QString::fromUtf8("😠"), QString::fromUtf8("angry mad furious عصبانی خشمگین")},
    {QString::fromUtf8("😡"), QString::fromUtf8("rage angry red furious خشمگین عصبانی قرمز")},
    {QString::fromUtf8("🤬"), QString::fromUtf8("swearing curse angry symbols فحش بد عصبانی")},
    {QString::fromUtf8("🤯"), QString::fromUtf8("exploding head mind blown shocked ذهن منفجر شوکه")},
    {QString::fromUtf8("😳"), QString::fromUtf8("flushed embarrassed surprised shocked شرمنده شوکه تعجب")},
    {QString::fromUtf8("🥵"), QString::fromUtf8("hot warm sweating heat گرم داغ عرق")},
    {QString::fromUtf8("🥶"), QString::fromUtf8("cold freezing frozen ice سرد یخ زده")},
    {QString::fromUtf8("😱"), QString::fromUtf8("scream horror fear shocked ترس وحشت جیغ")},
    {QString::fromUtf8("😨"), QString::fromUtf8("fearful scared afraid ترسیده وحشت‌زده")},
    {QString::fromUtf8("😰"), QString::fromUtf8("anxious worried sweat نگران مضطرب عرق")},
    {QString::fromUtf8("😥"), QString::fromUtf8("sad relieved disappointed sweat ناراحت")},
    {QString::fromUtf8("😓"), QString::fromUtf8("downcast sweat tired خسته عرق")},
    {QString::fromUtf8("🤗"), QString::fromUtf8("hug hugging warm embrace بغل آغوش گرم")},
    {QString::fromUtf8("🤔"), QString::fromUtf8("thinking think hmm wonder فکر فکرکردن تفکر")},
    {QString::fromUtf8("🤭"), QString::fromUtf8("giggle oops cover mouth خنده ریز دست دهان")},
    {QString::fromUtf8("🤫"), QString::fromUtf8("shush quiet secret silence هیس ساکت سکوت راز")},
    {QString::fromUtf8("🤥"), QString::fromUtf8("lying liar pinocchio nose دروغ دروغگو")},
    {QString::fromUtf8("😶"), QString::fromUtf8("mute silent no mouth ساکت بی‌صدا")},
    {QString::fromUtf8("😐"), QString::fromUtf8("neutral expressionless blank بی‌تفاوت")},
    {QString::fromUtf8("😑"), QString::fromUtf8("expressionless blank بی‌حالت")},
    {QString::fromUtf8("😬"), QString::fromUtf8("grimace awkward teeth ناراحت")},
    {QString::fromUtf8("🙄"), QString::fromUtf8("eye roll annoyed whatever چشم چرخاندن")},
    {QString::fromUtf8("😯"), QString::fromUtf8("hushed surprised quiet تعجب ساکت")},
    {QString::fromUtf8("😦"), QString::fromUtf8("frown open mouth surprise تعجب")},
    {QString::fromUtf8("😧"), QString::fromUtf8("anguish worried surprised نگران")},
    {QString::fromUtf8("😮"), QString::fromUtf8("open mouth wow surprise واو تعجب")},
    {QString::fromUtf8("😲"), QString::fromUtf8("astonished amazed shocked شگفت‌زده متعجب")},
    {QString::fromUtf8("🥱"), QString::fromUtf8("yawn bored tired sleepy خمیازه خسته خواب‌آلود")},
    {QString::fromUtf8("😴"), QString::fromUtf8("sleep sleeping zzz snore خواب خوابیده")},
    {QString::fromUtf8("🤤"), QString::fromUtf8("drool drooling hungry آب دهان گرسنه")},
    {QString::fromUtf8("😪"), QString::fromUtf8("sleepy tired bubble خواب‌آلود خسته")},
    {QString::fromUtf8("😵"), QString::fromUtf8("dizzy drunk spiral knocked گیج منگ")},
    {QString::fromUtf8("🤐"), QString::fromUtf8("zipper mouth shut secret zip دهان بسته زیپ")},
    {QString::fromUtf8("🥴"), QString::fromUtf8("woozy drunk tipsy dizzy مست گیج")},
    {QString::fromUtf8("🤢"), QString::fromUtf8("nauseated sick green حالت تهوع مریض")},
    {QString::fromUtf8("🤮"), QString::fromUtf8("vomit puke sick throw up استفراغ مریض")},
    {QString::fromUtf8("🤧"), QString::fromUtf8("sneeze tissue cold sick عطسه سرماخوردگی")},
    {QString::fromUtf8("😷"), QString::fromUtf8("mask sick doctor medical ماسک بیمار دکتر")},
    {QString::fromUtf8("🤒"), QString::fromUtf8("thermometer fever sick ill تب بیمار")},
    {QString::fromUtf8("🤕"), QString::fromUtf8("bandage hurt injured head زخمی باند سر")},
    {QString::fromUtf8("🤑"), QString::fromUtf8("money rich dollar greed پول ثروتمند دلار")},
    {QString::fromUtf8("🤠"), QString::fromUtf8("cowboy hat western country کابوی کلاه")},
    {QString::fromUtf8("😈"), QString::fromUtf8("devil evil smile horns شیطان بدجنس")},
    {QString::fromUtf8("👿"), QString::fromUtf8("devil angry evil imp شیطان عصبانی")},
    {QString::fromUtf8("👹"), QString::fromUtf8("ogre monster demon scary هیولا ترسناک")},
    {QString::fromUtf8("👺"), QString::fromUtf8("goblin tengu mask ماسک")},
    {QString::fromUtf8("🤡"), QString::fromUtf8("clown circus funny joke دلقک سیرک")},
    {QString::fromUtf8("💩"), QString::fromUtf8("poop poo shit funny مدفوع")},
    {QString::fromUtf8("👻"), QString::fromUtf8("ghost boo spooky halloween روح شبح جن")},
    {QString::fromUtf8("💀"), QString::fromUtf8("skull dead death skeleton جمجمه مرگ اسکلت")},
    {QString::fromUtf8("👽"), QString::fromUtf8("alien ufo space extraterrestrial آدم فضایی بیگانه")},
    {QString::fromUtf8("👾"), QString::fromUtf8("alien monster game space invader بازی هیولا")},
    {QString::fromUtf8("🤖"), QString::fromUtf8("robot bot machine ربات ماشین")},

    // ===== Animals & Nature =====
    {QString::fromUtf8("🐶"), QString::fromUtf8("dog puppy pet cute سگ توله حیوان خانگی")},
    {QString::fromUtf8("🐱"), QString::fromUtf8("cat kitten pet meow گربه بچه‌گربه")},
    {QString::fromUtf8("🐭"), QString::fromUtf8("mouse rat موش")},
    {QString::fromUtf8("🐹"), QString::fromUtf8("hamster pet cute همستر")},
    {QString::fromUtf8("🐰"), QString::fromUtf8("rabbit bunny cute خرگوش")},
    {QString::fromUtf8("🦊"), QString::fromUtf8("fox clever foxy روباه")},
    {QString::fromUtf8("🐻"), QString::fromUtf8("bear grizzly brown خرس")},
    {QString::fromUtf8("🐼"), QString::fromUtf8("panda bear cute پاندا خرس")},
    {QString::fromUtf8("🐻‍❄️"), QString::fromUtf8("polar bear white arctic ice خرس قطبی سفید")},
    {QString::fromUtf8("🐨"), QString::fromUtf8("koala bear australia کوالا")},
    {QString::fromUtf8("🐯"), QString::fromUtf8("tiger cat wild ببر")},
    {QString::fromUtf8("🦁"), QString::fromUtf8("lion king wild jungle شیر سلطان جنگل")},
    {QString::fromUtf8("🐮"), QString::fromUtf8("cow cattle گاو")},
    {QString::fromUtf8("🐷"), QString::fromUtf8("pig piggy خوک")},
    {QString::fromUtf8("🐽"), QString::fromUtf8("pig nose snout بینی خوک")},
    {QString::fromUtf8("🐸"), QString::fromUtf8("frog toad green قورباغه سبز")},
    {QString::fromUtf8("🐵"), QString::fromUtf8("monkey face میمون")},
    {QString::fromUtf8("🙈"), QString::fromUtf8("see no evil monkey shy میمون نبین خجالت")},
    {QString::fromUtf8("🙉"), QString::fromUtf8("hear no evil monkey میمون نشنو")},
    {QString::fromUtf8("🙊"), QString::fromUtf8("speak no evil monkey میمون نگو")},
    {QString::fromUtf8("🐒"), QString::fromUtf8("monkey animal میمون حیوان")},
    {QString::fromUtf8("🐔"), QString::fromUtf8("chicken hen bird مرغ پرنده")},
    {QString::fromUtf8("🐧"), QString::fromUtf8("penguin bird cold ice پنگوئن")},
    {QString::fromUtf8("🐦"), QString::fromUtf8("bird tweet fly پرنده")},
    {QString::fromUtf8("🐤"), QString::fromUtf8("chick baby bird جوجه")},
    {QString::fromUtf8("🐣"), QString::fromUtf8("hatching chick egg baby جوجه تخم‌مرغ")},
    {QString::fromUtf8("🐥"), QString::fromUtf8("chick baby front جوجه")},
    {QString::fromUtf8("🦆"), QString::fromUtf8("duck bird water اردک")},
    {QString::fromUtf8("🦅"), QString::fromUtf8("eagle bird prey عقاب")},
    {QString::fromUtf8("🦉"), QString::fromUtf8("owl bird night wise جغد شب")},
    {QString::fromUtf8("🦇"), QString::fromUtf8("bat vampire night خفاش شب")},
    {QString::fromUtf8("🐺"), QString::fromUtf8("wolf howl wild گرگ")},
    {QString::fromUtf8("🐗"), QString::fromUtf8("boar pig wild گراز")},
    {QString::fromUtf8("🐴"), QString::fromUtf8("horse pony اسب")},
    {QString::fromUtf8("🦄"), QString::fromUtf8("unicorn magic fantasy تک‌شاخ اسب شاخدار")},
    {QString::fromUtf8("🐝"), QString::fromUtf8("bee honey buzz sting زنبور عسل")},
    {QString::fromUtf8("🪱"), QString::fromUtf8("worm soil کرم")},
    {QString::fromUtf8("🐛"), QString::fromUtf8("bug caterpillar insect کرم حشره")},
    {QString::fromUtf8("🦋"), QString::fromUtf8("butterfly insect beautiful پروانه")},
    {QString::fromUtf8("🐌"), QString::fromUtf8("snail slow shell حلزون آهسته")},
    {QString::fromUtf8("🐞"), QString::fromUtf8("ladybug beetle insect red کفشدوزک")},
    {QString::fromUtf8("🐜"), QString::fromUtf8("ant insect small مورچه حشره")},
    {QString::fromUtf8("🪰"), QString::fromUtf8("fly insect buzz مگس")},
    {QString::fromUtf8("🪲"), QString::fromUtf8("beetle bug insect سوسک")},
    {QString::fromUtf8("🪳"), QString::fromUtf8("cockroach bug roach سوسک")},
    {QString::fromUtf8("🦟"), QString::fromUtf8("mosquito insect bite پشه")},
    {QString::fromUtf8("🦗"), QString::fromUtf8("cricket insect chirp جیرجیرک")},
    {QString::fromUtf8("🕷"), QString::fromUtf8("spider web creepy عنکبوت تار")},
    {QString::fromUtf8("🕸"), QString::fromUtf8("spider web cobweb تار عنکبوت")},
    {QString::fromUtf8("🦂"), QString::fromUtf8("scorpion sting عقرب نیش")},
    {QString::fromUtf8("🐢"), QString::fromUtf8("turtle tortoise slow shell لاک‌پشت آهسته")},
    {QString::fromUtf8("🐍"), QString::fromUtf8("snake serpent مار")},
    {QString::fromUtf8("🦎"), QString::fromUtf8("lizard reptile مارمولک")},
    {QString::fromUtf8("🦖"), QString::fromUtf8("dinosaur trex دایناسور")},
    {QString::fromUtf8("🦕"), QString::fromUtf8("dinosaur sauropod brontosaurus دایناسور")},
    {QString::fromUtf8("🐙"), QString::fromUtf8("octopus sea tentacle اختاپوس")},
    {QString::fromUtf8("🦑"), QString::fromUtf8("squid sea ocean ماهی مرکب")},
    {QString::fromUtf8("🦐"), QString::fromUtf8("shrimp prawn seafood میگو")},
    {QString::fromUtf8("🦞"), QString::fromUtf8("lobster seafood خرچنگ")},
    {QString::fromUtf8("🦀"), QString::fromUtf8("crab sea خرچنگ")},
    {QString::fromUtf8("🐡"), QString::fromUtf8("blowfish puffer fish بادکنک‌ماهی")},
    {QString::fromUtf8("🐠"), QString::fromUtf8("tropical fish ماهی")},
    {QString::fromUtf8("🐟"), QString::fromUtf8("fish sea ocean ماهی دریا")},
    {QString::fromUtf8("🐬"), QString::fromUtf8("dolphin sea ocean smart دلفین")},
    {QString::fromUtf8("🐳"), QString::fromUtf8("whale sea ocean spout نهنگ")},
    {QString::fromUtf8("🐋"), QString::fromUtf8("whale ocean sea نهنگ اقیانوس")},
    {QString::fromUtf8("🦈"), QString::fromUtf8("shark danger sea ocean کوسه")},
    {QString::fromUtf8("🦭"), QString::fromUtf8("seal sea فک دریایی")},
    {QString::fromUtf8("🐊"), QString::fromUtf8("crocodile alligator تمساح")},
    {QString::fromUtf8("🐅"), QString::fromUtf8("tiger wild cat ببر")},
    {QString::fromUtf8("🐆"), QString::fromUtf8("leopard cheetah wild پلنگ یوزپلنگ")},
    {QString::fromUtf8("🦓"), QString::fromUtf8("zebra stripes گورخر")},
    {QString::fromUtf8("🦍"), QString::fromUtf8("gorilla ape strong گوریل")},
    {QString::fromUtf8("🦧"), QString::fromUtf8("orangutan ape اورانگوتان")},
    {QString::fromUtf8("🦣"), QString::fromUtf8("mammoth woolly extinct ماموت")},
    {QString::fromUtf8("🐘"), QString::fromUtf8("elephant big trunk فیل")},
    {QString::fromUtf8("🦛"), QString::fromUtf8("hippo hippopotamus اسب آبی")},
    {QString::fromUtf8("🦏"), QString::fromUtf8("rhino rhinoceros horn کرگدن")},
    {QString::fromUtf8("🐪"), QString::fromUtf8("camel desert one hump شتر بیابان")},
    {QString::fromUtf8("🐫"), QString::fromUtf8("camel desert two humps شتر دوکوهانه")},
    {QString::fromUtf8("🦒"), QString::fromUtf8("giraffe tall spots زرافه")},
    {QString::fromUtf8("🦘"), QString::fromUtf8("kangaroo australia jump کانگورو")},
    {QString::fromUtf8("🦬"), QString::fromUtf8("bison buffalo گاومیش")},
    {QString::fromUtf8("🐃"), QString::fromUtf8("water buffalo گاومیش")},
    {QString::fromUtf8("🐂"), QString::fromUtf8("ox bull گاو نر")},
    {QString::fromUtf8("🐄"), QString::fromUtf8("cow dairy milk گاو شیری")},
    {QString::fromUtf8("🐎"), QString::fromUtf8("horse racing fast اسب مسابقه")},
    {QString::fromUtf8("🐖"), QString::fromUtf8("pig pork خوک")},
    {QString::fromUtf8("🐏"), QString::fromUtf8("ram sheep horn قوچ")},
    {QString::fromUtf8("🐑"), QString::fromUtf8("sheep lamb wool گوسفند بره پشم")},
    {QString::fromUtf8("🦙"), QString::fromUtf8("llama alpaca لاما")},
    {QString::fromUtf8("🐐"), QString::fromUtf8("goat بز")},
    {QString::fromUtf8("🦌"), QString::fromUtf8("deer stag antler گوزن آهو")},
    {QString::fromUtf8("🐕"), QString::fromUtf8("dog pet سگ")},
    {QString::fromUtf8("🐩"), QString::fromUtf8("poodle dog fancy پودل سگ")},
    {QString::fromUtf8("🦮"), QString::fromUtf8("guide dog service سگ راهنما")},
    {QString::fromUtf8("🐕‍🦺"), QString::fromUtf8("service dog vest سگ خدماتی")},
    {QString::fromUtf8("🐈"), QString::fromUtf8("cat pet گربه")},
    {QString::fromUtf8("🐈‍⬛"), QString::fromUtf8("black cat گربه سیاه")},
    {QString::fromUtf8("🪶"), QString::fromUtf8("feather bird quill پر")},
    {QString::fromUtf8("🐓"), QString::fromUtf8("rooster chicken cock خروس")},
    {QString::fromUtf8("🦃"), QString::fromUtf8("turkey bird بوقلمون")},
    {QString::fromUtf8("🦤"), QString::fromUtf8("dodo bird extinct دودو")},
    {QString::fromUtf8("🦚"), QString::fromUtf8("peacock bird feather طاووس")},
    {QString::fromUtf8("🦜"), QString::fromUtf8("parrot bird colorful طوطی")},
    {QString::fromUtf8("🦢"), QString::fromUtf8("swan bird elegant white قو")},
    {QString::fromUtf8("🦩"), QString::fromUtf8("flamingo bird pink فلامینگو")},
    {QString::fromUtf8("🕊"), QString::fromUtf8("dove peace bird white کبوتر صلح")},
    {QString::fromUtf8("🐇"), QString::fromUtf8("rabbit bunny خرگوش")},
    {QString::fromUtf8("🦝"), QString::fromUtf8("raccoon راکون")},
    {QString::fromUtf8("🦨"), QString::fromUtf8("skunk smell اسکانک")},
    {QString::fromUtf8("🦡"), QString::fromUtf8("badger گورکن")},
    {QString::fromUtf8("🦫"), QString::fromUtf8("beaver dam سگ آبی")},
    {QString::fromUtf8("🦦"), QString::fromUtf8("otter sea cute سمور")},
    {QString::fromUtf8("🦥"), QString::fromUtf8("sloth slow lazy تنبل")},
    {QString::fromUtf8("🐁"), QString::fromUtf8("mouse small موش کوچک")},
    {QString::fromUtf8("🐀"), QString::fromUtf8("rat rodent موش صحرایی")},
    {QString::fromUtf8("🐿"), QString::fromUtf8("squirrel chipmunk nut سنجاب")},
    {QString::fromUtf8("🦔"), QString::fromUtf8("hedgehog spikes جوجه‌تیغی")},

    // ===== Food & Drink =====
    {QString::fromUtf8("🍏"), QString::fromUtf8("green apple fruit سیب سبز میوه")},
    {QString::fromUtf8("🍎"), QString::fromUtf8("red apple fruit سیب قرمز میوه")},
    {QString::fromUtf8("🍐"), QString::fromUtf8("pear fruit گلابی میوه")},
    {QString::fromUtf8("🍊"), QString::fromUtf8("orange tangerine fruit پرتقال نارنگی")},
    {QString::fromUtf8("🍋"), QString::fromUtf8("lemon citrus sour لیمو ترش")},
    {QString::fromUtf8("🍌"), QString::fromUtf8("banana fruit yellow موز")},
    {QString::fromUtf8("🍉"), QString::fromUtf8("watermelon fruit summer هندوانه تابستان")},
    {QString::fromUtf8("🍇"), QString::fromUtf8("grapes fruit wine انگور")},
    {QString::fromUtf8("🍓"), QString::fromUtf8("strawberry fruit red توت‌فرنگی")},
    {QString::fromUtf8("🫐"), QString::fromUtf8("blueberry fruit بلوبری")},
    {QString::fromUtf8("🍈"), QString::fromUtf8("melon fruit طالبی")},
    {QString::fromUtf8("🍒"), QString::fromUtf8("cherry fruit red گیلاس")},
    {QString::fromUtf8("🍑"), QString::fromUtf8("peach fruit هلو")},
    {QString::fromUtf8("🥭"), QString::fromUtf8("mango fruit tropical انبه")},
    {QString::fromUtf8("🍍"), QString::fromUtf8("pineapple fruit tropical آناناس")},
    {QString::fromUtf8("🥥"), QString::fromUtf8("coconut tropical نارگیل")},
    {QString::fromUtf8("🥝"), QString::fromUtf8("kiwi fruit green کیوی")},
    {QString::fromUtf8("🍅"), QString::fromUtf8("tomato red vegetable گوجه")},
    {QString::fromUtf8("🍆"), QString::fromUtf8("eggplant aubergine purple بادمجان")},
    {QString::fromUtf8("🥑"), QString::fromUtf8("avocado fruit green آووکادو")},
    {QString::fromUtf8("🥦"), QString::fromUtf8("broccoli vegetable green کلم بروکلی")},
    {QString::fromUtf8("🥬"), QString::fromUtf8("leafy green lettuce vegetable کاهو سبزی")},
    {QString::fromUtf8("🥒"), QString::fromUtf8("cucumber vegetable green خیار")},
    {QString::fromUtf8("🌶"), QString::fromUtf8("hot pepper chili spicy فلفل تند")},
    {QString::fromUtf8("🫑"), QString::fromUtf8("bell pepper vegetable فلفل دلمه")},
    {QString::fromUtf8("🌽"), QString::fromUtf8("corn maize ذرت")},
    {QString::fromUtf8("🥕"), QString::fromUtf8("carrot vegetable orange هویج")},
    {QString::fromUtf8("🫒"), QString::fromUtf8("olive oil زیتون")},
    {QString::fromUtf8("🧄"), QString::fromUtf8("garlic cooking سیر")},
    {QString::fromUtf8("🧅"), QString::fromUtf8("onion cooking پیاز")},
    {QString::fromUtf8("🥔"), QString::fromUtf8("potato vegetable سیب‌زمینی")},
    {QString::fromUtf8("🍠"), QString::fromUtf8("sweet potato yam سیب‌زمینی شیرین")},
    {QString::fromUtf8("🥐"), QString::fromUtf8("croissant bread french pastry کروسان نان")},
    {QString::fromUtf8("🥯"), QString::fromUtf8("bagel bread بیگل نان")},
    {QString::fromUtf8("🍞"), QString::fromUtf8("bread loaf toast نان")},
    {QString::fromUtf8("🥖"), QString::fromUtf8("baguette french bread نان فرانسوی")},
    {QString::fromUtf8("🥨"), QString::fromUtf8("pretzel snack bread پرتزل")},
    {QString::fromUtf8("🧀"), QString::fromUtf8("cheese dairy yellow پنیر")},
    {QString::fromUtf8("🥚"), QString::fromUtf8("egg breakfast تخم‌مرغ")},
    {QString::fromUtf8("🍳"), QString::fromUtf8("fried egg cooking breakfast تخم‌مرغ نیمرو صبحانه")},
    {QString::fromUtf8("🧈"), QString::fromUtf8("butter dairy کره")},
    {QString::fromUtf8("🥞"), QString::fromUtf8("pancake breakfast پنکیک صبحانه")},
    {QString::fromUtf8("🧇"), QString::fromUtf8("waffle breakfast وافل")},
    {QString::fromUtf8("🥓"), QString::fromUtf8("bacon meat breakfast بیکن گوشت")},
    {QString::fromUtf8("🥩"), QString::fromUtf8("meat steak beef cut گوشت استیک")},
    {QString::fromUtf8("🍗"), QString::fromUtf8("chicken leg drumstick ران مرغ")},
    {QString::fromUtf8("🍖"), QString::fromUtf8("meat bone rib گوشت استخوان")},
    {QString::fromUtf8("🦴"), QString::fromUtf8("bone dog استخوان")},
    {QString::fromUtf8("🌭"), QString::fromUtf8("hotdog sausage هات‌داگ سوسیس")},
    {QString::fromUtf8("🍔"), QString::fromUtf8("hamburger burger fast food همبرگر برگر فست فود")},
    {QString::fromUtf8("🍟"), QString::fromUtf8("fries french fries fast food سیب‌زمینی سرخ‌شده")},
    {QString::fromUtf8("🍕"), QString::fromUtf8("pizza slice italian پیتزا ایتالیایی")},
    {QString::fromUtf8("🫓"), QString::fromUtf8("flatbread naan نان")},
    {QString::fromUtf8("🥪"), QString::fromUtf8("sandwich lunch ساندویچ")},
    {QString::fromUtf8("🥙"), QString::fromUtf8("pita falafel wrap فلافل")},
    {QString::fromUtf8("🧆"), QString::fromUtf8("falafel vegetarian فلافل")},
    {QString::fromUtf8("🌮"), QString::fromUtf8("taco mexican food تاکو مکزیکی")},
    {QString::fromUtf8("🌯"), QString::fromUtf8("burrito wrap mexican بوریتو")},
    {QString::fromUtf8("🫔"), QString::fromUtf8("tamale mexican food تامالی")},
    {QString::fromUtf8("🥗"), QString::fromUtf8("salad healthy green vegetable سالاد سبزیجات")},
    {QString::fromUtf8("🥘"), QString::fromUtf8("stew pot cooking خورشت قابلمه")},
    {QString::fromUtf8("🫕"), QString::fromUtf8("fondue cheese فوندو پنیر")},
    {QString::fromUtf8("🥫"), QString::fromUtf8("canned food tin کنسرو")},
    {QString::fromUtf8("🍝"), QString::fromUtf8("spaghetti pasta italian اسپاگتی پاستا ماکارونی")},
    {QString::fromUtf8("🍜"), QString::fromUtf8("noodle ramen soup نودل رامن سوپ")},
    {QString::fromUtf8("🍲"), QString::fromUtf8("pot stew soup food آبگوشت سوپ")},
    {QString::fromUtf8("🍛"), QString::fromUtf8("curry rice indian کاری برنج")},
    {QString::fromUtf8("🍣"), QString::fromUtf8("sushi japanese fish سوشی ژاپنی")},
    {QString::fromUtf8("🍱"), QString::fromUtf8("bento box lunch japanese بنتو ژاپنی")},
    {QString::fromUtf8("🥟"), QString::fromUtf8("dumpling chinese dim sum دامپلینگ")},
    {QString::fromUtf8("🦪"), QString::fromUtf8("oyster shell sea صدف")},
    {QString::fromUtf8("🍤"), QString::fromUtf8("shrimp prawn fried میگو سرخ‌شده")},
    {QString::fromUtf8("🍙"), QString::fromUtf8("rice ball onigiri japanese برنج")},
    {QString::fromUtf8("🍚"), QString::fromUtf8("rice cooked white برنج")},
    {QString::fromUtf8("🍘"), QString::fromUtf8("rice cracker snack بیسکویت برنجی")},
    {QString::fromUtf8("🍥"), QString::fromUtf8("fish cake narutomaki ناروتو")},
    {QString::fromUtf8("🥠"), QString::fromUtf8("fortune cookie بیسکویت")},
    {QString::fromUtf8("🥮"), QString::fromUtf8("mooncake cake کیک")},
    {QString::fromUtf8("🍢"), QString::fromUtf8("oden skewer سیخ")},
    {QString::fromUtf8("🍡"), QString::fromUtf8("dango sweet japanese دانگو")},
    {QString::fromUtf8("🍧"), QString::fromUtf8("shaved ice dessert cold بستنی یخی")},
    {QString::fromUtf8("🍨"), QString::fromUtf8("ice cream dessert sweet بستنی دسر")},
    {QString::fromUtf8("🍦"), QString::fromUtf8("ice cream cone soft serve بستنی قیفی")},
    {QString::fromUtf8("🥧"), QString::fromUtf8("pie dessert baked پای")},
    {QString::fromUtf8("🧁"), QString::fromUtf8("cupcake cake sweet dessert کاپ‌کیک")},
    {QString::fromUtf8("🍰"), QString::fromUtf8("cake slice birthday dessert sweet کیک دسر شیرینی")},
    {QString::fromUtf8("🎂"), QString::fromUtf8("birthday cake candle celebration کیک تولد شمع جشن")},
    {QString::fromUtf8("🍮"), QString::fromUtf8("custard pudding flan دسر پودینگ")},
    {QString::fromUtf8("🍭"), QString::fromUtf8("lollipop candy sweet آبنبات شیرینی")},
    {QString::fromUtf8("🍬"), QString::fromUtf8("candy sweet wrapper شکلات آبنبات")},
    {QString::fromUtf8("🍫"), QString::fromUtf8("chocolate bar sweet شکلات")},
    {QString::fromUtf8("🍿"), QString::fromUtf8("popcorn movie snack پاپ‌کورن ذرت‌بوداده سینما")},
    {QString::fromUtf8("🍩"), QString::fromUtf8("donut doughnut sweet دونات")},
    {QString::fromUtf8("🍪"), QString::fromUtf8("cookie biscuit sweet کلوچه بیسکویت")},
    {QString::fromUtf8("🌰"), QString::fromUtf8("chestnut nut بلوط")},
    {QString::fromUtf8("🥜"), QString::fromUtf8("peanut nut بادام‌زمینی")},
    {QString::fromUtf8("🍯"), QString::fromUtf8("honey pot sweet bee عسل")},
    {QString::fromUtf8("🥛"), QString::fromUtf8("milk glass drink شیر لیوان")},
    {QString::fromUtf8("🍼"), QString::fromUtf8("baby bottle milk شیشه شیر نوزاد")},
    {QString::fromUtf8("🫖"), QString::fromUtf8("teapot tea قوری چای")},
    {QString::fromUtf8("☕️"), QString::fromUtf8("coffee hot drink cup قهوه نوشیدنی فنجان چای")},
    {QString::fromUtf8("🍵"), QString::fromUtf8("tea green matcha cup چای سبز فنجان")},
    {QString::fromUtf8("🧃"), QString::fromUtf8("juice box drink آبمیوه")},
    {QString::fromUtf8("🥤"), QString::fromUtf8("cup straw soda drink لیوان نی نوشابه")},
    {QString::fromUtf8("🧋"), QString::fromUtf8("bubble tea boba drink چای حبابی")},
    {QString::fromUtf8("🍶"), QString::fromUtf8("sake japanese rice wine ساکه")},
    {QString::fromUtf8("🍺"), QString::fromUtf8("beer mug drink آبجو")},
    {QString::fromUtf8("🍻"), QString::fromUtf8("beer cheers clink toast آبجو سلامتی")},
    {QString::fromUtf8("🥂"), QString::fromUtf8("champagne cheers toast celebrate سلامتی جشن شامپاین")},
    {QString::fromUtf8("🍷"), QString::fromUtf8("wine glass red drink شراب")},
    {QString::fromUtf8("🥃"), QString::fromUtf8("whisky tumbler drink ویسکی")},
    {QString::fromUtf8("🍸"), QString::fromUtf8("cocktail martini drink کوکتل")},
    {QString::fromUtf8("🍹"), QString::fromUtf8("tropical drink cocktail نوشیدنی")},
    {QString::fromUtf8("🧉"), QString::fromUtf8("mate drink tea نوشیدنی")},
    {QString::fromUtf8("🍾"), QString::fromUtf8("champagne bottle celebrate party شامپاین جشن")},
    {QString::fromUtf8("🧊"), QString::fromUtf8("ice cube cold یخ")},
    {QString::fromUtf8("🥄"), QString::fromUtf8("spoon utensil قاشق")},
    {QString::fromUtf8("🍴"), QString::fromUtf8("fork knife utensil cutlery چنگال کارد")},
    {QString::fromUtf8("🍽"), QString::fromUtf8("plate fork knife dinner بشقاب")},
    {QString::fromUtf8("🥣"), QString::fromUtf8("bowl spoon cereal soup کاسه")},
    {QString::fromUtf8("🥡"), QString::fromUtf8("takeout box food جعبه غذا")},
    {QString::fromUtf8("🥢"), QString::fromUtf8("chopsticks asian food چوب غذاخوری")},
    {QString::fromUtf8("🧂"), QString::fromUtf8("salt shaker seasoning نمک")},

    // ===== Activity =====
    {QString::fromUtf8("⚽️"), QString::fromUtf8("soccer football ball sport فوتبال توپ ورزش")},
    {QString::fromUtf8("🏀"), QString::fromUtf8("basketball ball sport بسکتبال توپ")},
    {QString::fromUtf8("🏈"), QString::fromUtf8("football american sport فوتبال آمریکایی")},
    {QString::fromUtf8("⚾️"), QString::fromUtf8("baseball ball sport بیسبال")},
    {QString::fromUtf8("🥎"), QString::fromUtf8("softball ball sport سافتبال")},
    {QString::fromUtf8("🎾"), QString::fromUtf8("tennis ball racket sport تنیس")},
    {QString::fromUtf8("🏐"), QString::fromUtf8("volleyball ball sport والیبال")},
    {QString::fromUtf8("🏉"), QString::fromUtf8("rugby ball sport راگبی")},
    {QString::fromUtf8("🥏"), QString::fromUtf8("flying disc frisbee فریزبی")},
    {QString::fromUtf8("🎱"), QString::fromUtf8("pool billiard eight ball بیلیارد")},
    {QString::fromUtf8("🪀"), QString::fromUtf8("yoyo toy یویو")},
    {QString::fromUtf8("🏓"), QString::fromUtf8("ping pong table tennis پینگ‌پنگ تنیس")},
    {QString::fromUtf8("🏸"), QString::fromUtf8("badminton shuttlecock بدمینتون")},
    {QString::fromUtf8("🏒"), QString::fromUtf8("ice hockey stick puck هاکی")},
    {QString::fromUtf8("🏑"), QString::fromUtf8("field hockey هاکی")},
    {QString::fromUtf8("🥍"), QString::fromUtf8("lacrosse لاکراس")},
    {QString::fromUtf8("🏏"), QString::fromUtf8("cricket bat ball کریکت")},
    {QString::fromUtf8("🪃"), QString::fromUtf8("boomerang throw بومرنگ")},
    {QString::fromUtf8("🥅"), QString::fromUtf8("goal net دروازه تور")},
    {QString::fromUtf8("⛳️"), QString::fromUtf8("golf flag hole گلف")},
    {QString::fromUtf8("🪁"), QString::fromUtf8("kite flying wind بادبادک")},
    {QString::fromUtf8("🏹"), QString::fromUtf8("bow arrow archery تیر کمان")},
    {QString::fromUtf8("🎣"), QString::fromUtf8("fishing rod ماهیگیری")},
    {QString::fromUtf8("🤿"), QString::fromUtf8("diving mask scuba snorkel غواصی ماسک")},
    {QString::fromUtf8("🥊"), QString::fromUtf8("boxing glove fight punch بوکس مبارزه مشت")},
    {QString::fromUtf8("🥋"), QString::fromUtf8("martial arts karate judo کاراته جودو رزمی")},
    {QString::fromUtf8("🎽"), QString::fromUtf8("running shirt sport ورزش دو")},
    {QString::fromUtf8("🛹"), QString::fromUtf8("skateboard skate اسکیت‌بورد")},
    {QString::fromUtf8("🛼"), QString::fromUtf8("roller skate اسکیت")},
    {QString::fromUtf8("🛷"), QString::fromUtf8("sled sledge snow سورتمه برف")},
    {QString::fromUtf8("⛸"), QString::fromUtf8("ice skate اسکیت یخ")},
    {QString::fromUtf8("🥌"), QString::fromUtf8("curling stone کرلینگ")},
    {QString::fromUtf8("🎿"), QString::fromUtf8("ski skiing snow اسکی برف")},
    {QString::fromUtf8("⛷"), QString::fromUtf8("skier skiing snow اسکی‌باز")},
    {QString::fromUtf8("🏂"), QString::fromUtf8("snowboard snowboarding snow اسنوبورد")},
    {QString::fromUtf8("🪂"), QString::fromUtf8("parachute skydive چتر نجات")},
    {QString::fromUtf8("🏆"), QString::fromUtf8("trophy winner champion gold cup جام قهرمانی برنده طلا")},
    {QString::fromUtf8("🥇"), QString::fromUtf8("gold medal first winner مدال طلا اول برنده")},
    {QString::fromUtf8("🥈"), QString::fromUtf8("silver medal second مدال نقره دوم")},
    {QString::fromUtf8("🥉"), QString::fromUtf8("bronze medal third مدال برنز سوم")},
    {QString::fromUtf8("🏅"), QString::fromUtf8("medal sports مدال ورزشی")},
    {QString::fromUtf8("🎖"), QString::fromUtf8("military medal honor مدال نظامی افتخار")},
    {QString::fromUtf8("🏵"), QString::fromUtf8("rosette flower نشان")},
    {QString::fromUtf8("🎗"), QString::fromUtf8("ribbon reminder روبان یادبود")},
    {QString::fromUtf8("🎫"), QString::fromUtf8("ticket event بلیت")},
    {QString::fromUtf8("🎟"), QString::fromUtf8("admission ticket بلیت ورودی")},
    {QString::fromUtf8("🎪"), QString::fromUtf8("circus tent show سیرک چادر")},
    {QString::fromUtf8("🎭"), QString::fromUtf8("theater drama mask performing arts تئاتر نمایش ماسک")},
    {QString::fromUtf8("🩰"), QString::fromUtf8("ballet shoes dance رقص باله")},
    {QString::fromUtf8("🎨"), QString::fromUtf8("art paint palette color نقاشی هنر رنگ پالت")},
    {QString::fromUtf8("🎬"), QString::fromUtf8("movie clapper film cinema فیلم سینما")},
    {QString::fromUtf8("🎤"), QString::fromUtf8("microphone sing karaoke voice میکروفون آواز خوانندگی")},
    {QString::fromUtf8("🎧"), QString::fromUtf8("headphone music listen audio هدفون موسیقی")},
    {QString::fromUtf8("🎼"), QString::fromUtf8("music score notes نت موسیقی")},
    {QString::fromUtf8("🎹"), QString::fromUtf8("piano keyboard music instrument پیانو کیبورد ساز")},
    {QString::fromUtf8("🥁"), QString::fromUtf8("drum beat percussion طبل درام")},
    {QString::fromUtf8("🪘"), QString::fromUtf8("long drum percussion طبل")},
    {QString::fromUtf8("🎷"), QString::fromUtf8("saxophone sax jazz music ساکسیفون جاز")},
    {QString::fromUtf8("🎺"), QString::fromUtf8("trumpet horn music شیپور ترومپت")},
    {QString::fromUtf8("🪗"), QString::fromUtf8("accordion music آکاردئون")},
    {QString::fromUtf8("🎸"), QString::fromUtf8("guitar rock music electric گیتار راک موسیقی")},
    {QString::fromUtf8("🪕"), QString::fromUtf8("banjo music بنجو")},
    {QString::fromUtf8("🎻"), QString::fromUtf8("violin fiddle music classical ویولن کلاسیک")},
    {QString::fromUtf8("🎲"), QString::fromUtf8("dice game luck chance تاس بازی شانس")},
    {QString::fromUtf8("♟"), QString::fromUtf8("chess piece pawn شطرنج مهره")},
    {QString::fromUtf8("🎯"), QString::fromUtf8("target bullseye dart هدف دارت")},
    {QString::fromUtf8("🎳"), QString::fromUtf8("bowling ball pin بولینگ")},
    {QString::fromUtf8("🎮"), QString::fromUtf8("game controller video play بازی کنترلر گیم")},
    {QString::fromUtf8("🎰"), QString::fromUtf8("slot machine casino gamble اسلات کازینو قمار")},
    {QString::fromUtf8("🧩"), QString::fromUtf8("puzzle piece jigsaw پازل")},

    // ===== Travel & Places =====
    {QString::fromUtf8("🚗"), QString::fromUtf8("car automobile vehicle ماشین خودرو اتومبیل")},
    {QString::fromUtf8("🚕"), QString::fromUtf8("taxi cab تاکسی ماشین")},
    {QString::fromUtf8("🚙"), QString::fromUtf8("suv blue car vehicle ماشین آبی شاسی بلند")},
    {QString::fromUtf8("🚌"), QString::fromUtf8("bus vehicle اتوبوس")},
    {QString::fromUtf8("🚓"), QString::fromUtf8("police car cop ماشین پلیس")},
    {QString::fromUtf8("🚑"), QString::fromUtf8("ambulance hospital آمبولانس بیمارستان")},
    {QString::fromUtf8("🚒"), QString::fromUtf8("fire engine fire truck ماشین آتش نشانی")},
    {QString::fromUtf8("🚚"), QString::fromUtf8("delivery truck کامیون باربری")},
    {QString::fromUtf8("🚜"), QString::fromUtf8("tractor agriculture تراکتور کشاورزی")},
    {QString::fromUtf8("🛵"), QString::fromUtf8("motor scooter موتور گازی اسکوتر")},
    {QString::fromUtf8("🏍"), QString::fromUtf8("motorcycle bike موتور سیکلت")},
    {QString::fromUtf8("🚲"), QString::fromUtf8("bicycle bike دوچرخه")},
    {QString::fromUtf8("🛴"), QString::fromUtf8("kick scooter اسکوتر")},
    {QString::fromUtf8("🚂"), QString::fromUtf8("locomotive train قطار لوکوموتیو")},
    {QString::fromUtf8("🚆"), QString::fromUtf8("train railway قطار راه آهن")},
    {QString::fromUtf8("🚁"), QString::fromUtf8("helicopter هلیکوپتر بالگرد")},
    {QString::fromUtf8("✈️"), QString::fromUtf8("airplane plane flight هواپیما پرواز")},
    {QString::fromUtf8("🚀"), QString::fromUtf8("rocket space موشک فضا")},
    {QString::fromUtf8("🛸"), QString::fromUtf8("flying saucer ufo بشقاب پرنده فضایی")},
    {QString::fromUtf8("🛰"), QString::fromUtf8("satellite space ماهواره")},
    {QString::fromUtf8("⛵️"), QString::fromUtf8("sailboat sea قایق بادبانی دریا")},
    {QString::fromUtf8("🛳"), QString::fromUtf8("passenger ship cruise کشتی مسافربری تفریحی")},
    {QString::fromUtf8("🚢"), QString::fromUtf8("ship boat کشتی قایق")},
    {QString::fromUtf8("⚓️"), QString::fromUtf8("anchor ship لنگر کشتی")},
    {QString::fromUtf8("⛽️"), QString::fromUtf8("fuel pump gas station پمپ بنزین سوخت")},
    {QString::fromUtf8("🚦"), QString::fromUtf8("traffic light چراغ راهنمایی")},
    {QString::fromUtf8("🗺"), QString::fromUtf8("world map نقشه جهان")},
    {QString::fromUtf8("🗽"), QString::fromUtf8("statue of liberty مجسمه آزادی")},
    {QString::fromUtf8("🗼"), QString::fromUtf8("tokyo tower برج توکیو")},
    {QString::fromUtf8("🏰"), QString::fromUtf8("castle قلعه قصر")},
    {QString::fromUtf8("🏟"), QString::fromUtf8("stadium sports استادیوم ورزشگاه")},
    {QString::fromUtf8("🎡"), QString::fromUtf8("ferris wheel amusement park چرخ و فلک شهربازی")},
    {QString::fromUtf8("🎢"), QString::fromUtf8("roller coaster ترن هوایی")},
    {QString::fromUtf8("⛺️"), QString::fromUtf8("tent camp چادر کمپ خیمه")},
    {QString::fromUtf8("🏠"), QString::fromUtf8("house home building خانه منزل")},
    {QString::fromUtf8("🏡"), QString::fromUtf8("house with garden home خانه حیاط دار ویلا")},
    {QString::fromUtf8("🏢"), QString::fromUtf8("office building ساختمان دفتر کار اداری")},
    {QString::fromUtf8("🏥"), QString::fromUtf8("hospital clinic بیمارستان درمانگاه")},
    {QString::fromUtf8("🏦"), QString::fromUtf8("bank money بانک")},
    {QString::fromUtf8("🏨"), QString::fromUtf8("hotel هتل مسافرخانه")},
    {QString::fromUtf8("🏫"), QString::fromUtf8("school education مدرسه آموزشگاه")},
    {QString::fromUtf8("🕌"), QString::fromUtf8("mosque islam religion مسجد اسلام دین")},
    {QString::fromUtf8("🕋"), QString::fromUtf8("kaaba islam mecca کعبه مکه اسلام")},
    {QString::fromUtf8("⛪️"), QString::fromUtf8("church christian کلیسا مسیحیت")},
    {QString::fromUtf8("🌅"), QString::fromUtf8("sunrise morning طلوع خورشید صبح")},
    {QString::fromUtf8("🌄"), QString::fromUtf8("sunrise over mountains طلوع کوهستان")},
    {QString::fromUtf8("🌠"), QString::fromUtf8("shooting star wish ستاره دنباله دار آرزو")},
    {QString::fromUtf8("🎇"), QString::fromUtf8("sparkler celebration فشفشه جشن شادی")},
    {QString::fromUtf8("🎆"), QString::fromUtf8("fireworks celebration آتش بازی جشن")},
    {QString::fromUtf8("🌇"), QString::fromUtf8("sunset evening غروب خورشید عصر")},
    {QString::fromUtf8("🌃"), QString::fromUtf8("night with stars شب پرستاره")},
    {QString::fromUtf8("🌌"), QString::fromUtf8("milky way galaxy space کهکشان راه شیری فضا")},

    // ===== Objects =====
    {QString::fromUtf8("⌚️"), QString::fromUtf8("watch time ساعت مچی زمان")},
    {QString::fromUtf8("📱"), QString::fromUtf8("mobile phone smartphone cell موبایل گوشی تلفن همراه")},
    {QString::fromUtf8("💻"), QString::fromUtf8("laptop computer pc لپ تاپ کامپیوتر رایانه")},
    {QString::fromUtf8("⌨️"), QString::fromUtf8("keyboard typing کیبورد صفحه کلید تایپ")},
    {QString::fromUtf8("🖥"), QString::fromUtf8("desktop computer monitor مانیتور کامپیوتر صفحه نمایش")},
    {QString::fromUtf8("🖨"), QString::fromUtf8("printer پرینتر چاپگر")},
    {QString::fromUtf8("🖱"), QString::fromUtf8("computer mouse ماوس موشواره")},
    {QString::fromUtf8("📷"), QString::fromUtf8("camera photo دوربین عکاسی عکس")},
    {QString::fromUtf8("📸"), QString::fromUtf8("camera with flash photo دوربین فلش دار عکس")},
    {QString::fromUtf8("📹"), QString::fromUtf8("video camera film دوربین فیلمبرداری ویدیو")},
    {QString::fromUtf8("🎥"), QString::fromUtf8("movie camera cinema دوربین سینما فیلم")},
    {QString::fromUtf8("📞"), QString::fromUtf8("telephone receiver call گوشی تلفن تماس")},
    {QString::fromUtf8("☎️"), QString::fromUtf8("telephone call تلفن تماس")},
    {QString::fromUtf8("📺"), QString::fromUtf8("television tv تلویزیون تی وی")},
    {QString::fromUtf8("📻"), QString::fromUtf8("radio رادیو")},
    {QString::fromUtf8("🎙"), QString::fromUtf8("studio microphone میکروفون استودیو صدا")},
    {QString::fromUtf8("⏱"), QString::fromUtf8("stopwatch timer کرنومتر زمان سنج")},
    {QString::fromUtf8("⏳"), QString::fromUtf8("hourglass sandglass time ساعت شنی زمان")},
    {QString::fromUtf8("🔋"), QString::fromUtf8("battery power باتری شارژ")},
    {QString::fromUtf8("🔌"), QString::fromUtf8("electric plug power دوشاخه پریز برق")},
    {QString::fromUtf8("💡"), QString::fromUtf8("light bulb idea ایده لامپ چراغ روشنایی")},
    {QString::fromUtf8("🔦"), QString::fromUtf8("flashlight torch چراغ قوه")},
    {QString::fromUtf8("🕯"), QString::fromUtf8("candle light شمع نور")},
    {QString::fromUtf8("🗑"), QString::fromUtf8("wastebasket trash سطل زباله آشغال")},
    {QString::fromUtf8("💸"), QString::fromUtf8("money with wings cash پول پرواز دلار")},
    {QString::fromUtf8("💵"), QString::fromUtf8("dollar banknote cash money پول دلار اسکناس")},
    {QString::fromUtf8("💶"), QString::fromUtf8("euro banknote cash یورو پول")},
    {QString::fromUtf8("💷"), QString::fromUtf8("pound banknote cash پوند پول")},
    {QString::fromUtf8("💰"), QString::fromUtf8("money bag wealth کیسه پول ثروت")},
    {QString::fromUtf8("💳"), QString::fromUtf8("credit card bank کارت اعتباری بانکی")},
    {QString::fromUtf8("💎"), QString::fromUtf8("gem diamond jewelry الماس جواهر نگین")},
    {QString::fromUtf8("⚖️"), QString::fromUtf8("balance scale justice ترازو عدالت قانون")},
    {QString::fromUtf8("🔧"), QString::fromUtf8("wrench tool آچار ابزار")},
    {QString::fromUtf8("🔨"), QString::fromUtf8("hammer tool چکش ابزار")},
    {QString::fromUtf8("⛏"), QString::fromUtf8("pickaxe tool کلنگ ابزار معدن")},
    {QString::fromUtf8("⚙️"), QString::fromUtf8("gear settings چرخ دنده تنظیمات")},
    {QString::fromUtf8("🧲"), QString::fromUtf8("magnet آهنربا")},
    {QString::fromUtf8("🔫"), QString::fromUtf8("water pistol gun weapon تفنگ آب پاش اسلحه")},
    {QString::fromUtf8("💣"), QString::fromUtf8("bomb explosion بمب انفجار")},
    {QString::fromUtf8("🧨"), QString::fromUtf8("firecracker ترقه")},
    {QString::fromUtf8("🪓"), QString::fromUtf8("axe wood تبر چوب")},
    {QString::fromUtf8("🔪"), QString::fromUtf8("kitchen knife چاقو کارد آشپزخانه")},
    {QString::fromUtf8("🗡"), QString::fromUtf8("dagger خنجر شمشیر کوتاه")},
    {QString::fromUtf8("⚔️"), QString::fromUtf8("crossed swords battle شمشیر متقاطع جنگ")},
    {QString::fromUtf8("🛡"), QString::fromUtf8("shield defense سپر دفاع")},
    {QString::fromUtf8("🚬"), QString::fromUtf8("cigarette smoke سیگار دود")},
    {QString::fromUtf8("⚰️"), QString::fromUtf8("coffin death تابوت مرگ")},
    {QString::fromUtf8("🪦"), QString::fromUtf8("headstone grave stone سنگ قبر گور")},
    {QString::fromUtf8("🔮"), QString::fromUtf8("crystal ball magic توپ بلوری جادو پیشگویی")},
    {QString::fromUtf8("📿"), QString::fromUtf8("prayer beads religion تسبیح ذکر مذهب")},
    {QString::fromUtf8("🧿"), QString::fromUtf8("nazar amulet evil eye چشم نظر چشم زخم")},
    {QString::fromUtf8("💉"), QString::fromUtf8("syringe needle blood سوزن آمپول سرنگ خون")},
    {QString::fromUtf8("💊"), QString::fromUtf8("pill medicine doctor قرص دارو پزشک")},
    {QString::fromUtf8("🩹"), QString::fromUtf8("adhesive bandage bandaid چسب زخم")},
    {QString::fromUtf8("🩺"), QString::fromUtf8("stethoscope doctor گوشی پزشکی دکتر")},
    {QString::fromUtf8("🚪"), QString::fromUtf8("door در درب")},
    {QString::fromUtf8("🛏"), QString::fromUtf8("bed sleep تخت خواب")},
    {QString::fromUtf8("🛋"), QString::fromUtf8("couch and lamp sofa مبل کاناپه")},
    {QString::fromUtf8("🚽"), QString::fromUtf8("toilet توالت دستشویی")},
    {QString::fromUtf8("🚿"), QString::fromUtf8("shower دوش حمام")},
    {QString::fromUtf8("🛁"), QString::fromUtf8("bathtub وان حمام")},
    {QString::fromUtf8("🧼"), QString::fromUtf8("soap wash صابون شستشو")},
    {QString::fromUtf8("🧽"), QString::fromUtf8("sponge wash اسفنج شستشو")},
    {QString::fromUtf8("🔑"), QString::fromUtf8("key lock کلید قفل")},
    {QString::fromUtf8("🧸"), QString::fromUtf8("teddy bear toy خرس عروسکی اسباب بازی")},
    {QString::fromUtf8("🎈"), QString::fromUtf8("balloon party بادکنک جشن")},
    {QString::fromUtf8("🎀"), QString::fromUtf8("ribbon bow روبان پاپیون")},
    {QString::fromUtf8("🎁"), QString::fromUtf8("wrapped gift present هدیه کادو جایزه")},
    {QString::fromUtf8("🎉"), QString::fromUtf8("party popper celebration جشن شادی مهمانی")},
    {QString::fromUtf8("✉️"), QString::fromUtf8("envelope mail پاکت نامه ایمیل")},
    {QString::fromUtf8("📦"), QString::fromUtf8("package box جعبه بسته پستی")},
    {QString::fromUtf8("📝"), QString::fromUtf8("memo write یادداشت نوشتن قلم")},
    {QString::fromUtf8("💼"), QString::fromUtf8("briefcase work کیف دستی کار")},
    {QString::fromUtf8("📁"), QString::fromUtf8("file folder پوشه پرونده")},
    {QString::fromUtf8("📅"), QString::fromUtf8("calendar date تقویم تاریخ")},
    {QString::fromUtf8("🔒"), QString::fromUtf8("locked closed قفل بسته امن")},
    {QString::fromUtf8("🔓"), QString::fromUtf8("unlocked open قفل باز")},

    // ===== Hearts & Symbols =====
    {QString::fromUtf8("❤️"), QString::fromUtf8("red heart love عشق قلب قرمز دوست داشتن دلبر عاشقی")},
    {QString::fromUtf8("🧡"), QString::fromUtf8("orange heart قلب نارنجی")},
    {QString::fromUtf8("💛"), QString::fromUtf8("yellow heart قلب زرد")},
    {QString::fromUtf8("💚"), QString::fromUtf8("green heart قلب سبز")},
    {QString::fromUtf8("💙"), QString::fromUtf8("blue heart قلب آبی")},
    {QString::fromUtf8("💜"), QString::fromUtf8("purple heart قلب بنفش")},
    {QString::fromUtf8("🖤"), QString::fromUtf8("black heart قلب مشکی سیاه")},
    {QString::fromUtf8("🤍"), QString::fromUtf8("white heart قلب سفید")},
    {QString::fromUtf8("🤎"), QString::fromUtf8("brown heart قلب قهوه ای")},
    {QString::fromUtf8("💔"), QString::fromUtf8("broken heart sad قلب شکسته جدایی")},
    {QString::fromUtf8("❣️"), QString::fromUtf8("heart exclamation علامت تعجب قلب")},
    {QString::fromUtf8("💕"), QString::fromUtf8("two hearts دو قلب عشق")},
    {QString::fromUtf8("💞"), QString::fromUtf8("revolving hearts قلب های چرخان")},
    {QString::fromUtf8("💓"), QString::fromUtf8("beating heart قلب تپنده")},
    {QString::fromUtf8("💗"), QString::fromUtf8("growing heart قلب در حال رشد")},
    {QString::fromUtf8("💖"), QString::fromUtf8("sparkling heart قلب درخشان درخشنده")},
    {QString::fromUtf8("💘"), QString::fromUtf8("heart with arrow قلب تیر خورده")},
    {QString::fromUtf8("💝"), QString::fromUtf8("heart with ribbon قلب هدیه کادو")},
    {QString::fromUtf8("☮️"), QString::fromUtf8("peace symbol نماد صلح")},
    {QString::fromUtf8("✝️"), QString::fromUtf8("latin cross religion صلیب مسیحیت")},
    {QString::fromUtf8("☪️"), QString::fromUtf8("star and crescent islam ستاره و هلال ماه اسلام")},
    {QString::fromUtf8("☯️"), QString::fromUtf8("yin yang یین و یانگ")},
    {QString::fromUtf8("✅"), QString::fromUtf8("check mark button done ok تیک تایید سبز انجام شد اره بله درست موافق قبول")},
    {QString::fromUtf8("❌"), QString::fromUtf8("cross mark x wrong ضربدر قرمز غلط لغو نه اشتباه رد ممنوع بستن")},
    {QString::fromUtf8("⚠️"), QString::fromUtf8("warning sign هشدار خطر اخطار")},
    {QString::fromUtf8("⛔️"), QString::fromUtf8("no entry sign ورود ممنوع")},
    {QString::fromUtf8("🚫"), QString::fromUtf8("prohibited no ممنوع غیرمجاز")},
    {QString::fromUtf8("💯"), QString::fromUtf8("hundred points 100 صد امتیاز کامل عالی")},
    {QString::fromUtf8("🆘"), QString::fromUtf8("sos help کمک اورژانس")},
    {QString::fromUtf8("🛑"), QString::fromUtf8("stop sign ایست توقف")},
    {QString::fromUtf8("🔥"), QString::fromUtf8("fire hot flame آتش داغ شعله عالی محشر داغون")},
    {QString::fromUtf8("✨"), QString::fromUtf8("sparkles stars shine ستاره درخشش برق")},
    {QString::fromUtf8("🌟"), QString::fromUtf8("glowing star ستاره درخشان طلایی")},
    {QString::fromUtf8("💫"), QString::fromUtf8("dizzy star سرگیجه ستاره")},
    {QString::fromUtf8("⭐"), QString::fromUtf8("star ستاره")},
    {QString::fromUtf8("💧"), QString::fromUtf8("droplet water قطره آب")},
    {QString::fromUtf8("💦"), QString::fromUtf8("sweat droplets water عرق آب خیس")},
    {QString::fromUtf8("💨"), QString::fromUtf8("dashing away wind باد حرکت سریع")},
    {QString::fromUtf8("⚡️"), QString::fromUtf8("high voltage lightning صاعقه رعد و برق انرژی")},
    {QString::fromUtf8("❄️"), QString::fromUtf8("snowflake snow برف دانه برف")},

    // ===== Recent Smileys & Gestures =====
    {QString::fromUtf8("🫶"), QString::fromUtf8("heart hands love دست قلب عشق")},
    {QString::fromUtf8("🫠"), QString::fromUtf8("melting face melt smile hot آب شدن ذوب لبخند")},
    {QString::fromUtf8("🫡"), QString::fromUtf8("saluting face salute respect سلام نظامی احترام")},
    {QString::fromUtf8("🥹"), QString::fromUtf8("face holding back tears proud بغض افتخار اشک")},
    {QString::fromUtf8("🫣"), QString::fromUtf8("peeking eye peek hide ترس نگاه یواشکی")},
    {QString::fromUtf8("🫤"), QString::fromUtf8("face with diagonal mouth confused skeptical گیج کج شک")},
    {QString::fromUtf8("🫥"), QString::fromUtf8("dotted line face invisible hide نامرئی مخفی پنهان")},
    {QString::fromUtf8("👍"), QString::fromUtf8("thumbs up like approve yes ok good لایک تایید آفرین اره بله موافق خوب عالی دمت گرم")},
    {QString::fromUtf8("👎"), QString::fromUtf8("thumbs down dislike no bad دیسلایک رد مخالف نه بد ضعیف نپسندیدن")},
    {QString::fromUtf8("👏"), QString::fromUtf8("clapping hands applause دست زدن تشویق")},
    {QString::fromUtf8("🙌"), QString::fromUtf8("raising hands hooray دستان بالا هورا")},
    {QString::fromUtf8("👐"), QString::fromUtf8("open hands hug دستان باز آغوش")},
    {QString::fromUtf8("🤲"), QString::fromUtf8("palms up together pray دستان دعا نیایش")},
    {QString::fromUtf8("🤝"), QString::fromUtf8("handshake deal دست دادن توافق همکاری معامله قرارداد تبریک")},
    {QString::fromUtf8("🙏"), QString::fromUtf8("folded hands pray please دعا تشکر خواهش نماز التماس ممنون یاعلی")},
    {QString::fromUtf8("✌️"), QString::fromUtf8("victory hand peace پیروزی صلح دو انگشت")},
    {QString::fromUtf8("🤞"), QString::fromUtf8("crossed fingers luck انگشتان متقاطع شانس")},
    {QString::fromUtf8("🤟"), QString::fromUtf8("love you gesture دوستت دارم")},
    {QString::fromUtf8("🤘"), QString::fromUtf8("sign of the horns rock شاخ راک")},
    {QString::fromUtf8("🤙"), QString::fromUtf8("call me hand تماس بگیر")},
    {QString::fromUtf8("👈"), QString::fromUtf8("backhand index pointing left اشاره چپ")},
    {QString::fromUtf8("👉"), QString::fromUtf8("backhand index pointing right اشاره راست")},
    {QString::fromUtf8("👆"), QString::fromUtf8("backhand index pointing up اشاره بالا")},
    {QString::fromUtf8("👇"), QString::fromUtf8("backhand index pointing down اشاره پایین")},
    {QString::fromUtf8("🖕"), QString::fromUtf8("middle finger انگشت وسط")},
    {QString::fromUtf8("✋"), QString::fromUtf8("raised hand stop دست بالا ایست")},
    {QString::fromUtf8("🤚"), QString::fromUtf8("raised back of hand پشت دست")},
    {QString::fromUtf8("🖐"), QString::fromUtf8("hand with fingers splayed دست باز")},
    {QString::fromUtf8("🖖"), QString::fromUtf8("vulcan salute اسپاک")},
    {QString::fromUtf8("👋"), QString::fromUtf8("waving hand hello goodbye بای سلام خداحافظ")},
    {QString::fromUtf8("💪"), QString::fromUtf8("flexed biceps strong muscle عضله بازو قوی قدرت")},
    {QString::fromUtf8("🦾"), QString::fromUtf8("mechanical arm robot دست مکانیکی ربات")},
    {QString::fromUtf8("🦵"), QString::fromUtf8("leg پا")},
    {QString::fromUtf8("🦿"), QString::fromUtf8("mechanical leg robot پای مکانیکی")},
    {QString::fromUtf8("🦶"), QString::fromUtf8("foot کف پا")},
    {QString::fromUtf8("👂"), QString::fromUtf8("ear listen گوش شنیدن")},
    {QString::fromUtf8("🦻"), QString::fromUtf8("ear with hearing aid سمعک")},
    {QString::fromUtf8("👃"), QString::fromUtf8("nose smell بینی دماغ بوییدن")},
    {QString::fromUtf8("🧠"), QString::fromUtf8("brain smart ذهن مغز باهوش")},
    {QString::fromUtf8("🫀"), QString::fromUtf8("anatomical heart قلب واقعی آناتومی")},
    {QString::fromUtf8("🫁"), QString::fromUtf8("lungs breath ریه شش تنفس")},
    {QString::fromUtf8("🦷"), QString::fromUtf8("tooth dentist دندان دندانپزشک")},
    {QString::fromUtf8("🦴"), QString::fromUtf8("bone استخوان")},
    {QString::fromUtf8("👀"), QString::fromUtf8("eyes look see چشم نگاه دیدن")},
    {QString::fromUtf8("👁"), QString::fromUtf8("eye چشم")},
    {QString::fromUtf8("👅"), QString::fromUtf8("tongue زبان")},
    {QString::fromUtf8("👄"), QString::fromUtf8("mouth lips دهان لب")},
    {QString::fromUtf8("💋"), QString::fromUtf8("kiss mark lips بوسه جای بوس لب")},

    // ===== People & Professions =====
    {QString::fromUtf8("👶"), QString::fromUtf8("baby infant child نوزاد بچه کودک")},
    {QString::fromUtf8("🧒"), QString::fromUtf8("child kid بچه کودک")},
    {QString::fromUtf8("👦"), QString::fromUtf8("boy پسر پسربچه")},
    {QString::fromUtf8("👧"), QString::fromUtf8("girl دختر دختربچه")},
    {QString::fromUtf8("🧑"), QString::fromUtf8("person adult آدم شخص فرد")},
    {QString::fromUtf8("👨"), QString::fromUtf8("man male مرد آقا")},
    {QString::fromUtf8("👩"), QString::fromUtf8("woman female زن خانم")},
    {QString::fromUtf8("🧔"), QString::fromUtf8("beard person مرد ریش دار ریشو")},
    {QString::fromUtf8("👱"), QString::fromUtf8("blond hair person مو بور بلوند")},
    {QString::fromUtf8("🧓"), QString::fromUtf8("older person elderly پیر سالمند مسن")},
    {QString::fromUtf8("👴"), QString::fromUtf8("old man grandfather پیرمرد پدربزرگ")},
    {QString::fromUtf8("👵"), QString::fromUtf8("old woman grandmother پیرزن مادربزرگ")},
    {QString::fromUtf8("👮"), QString::fromUtf8("police officer cop پلیس مامور افسر")},
    {QString::fromUtf8("👷"), QString::fromUtf8("construction worker کارگر ساختمانی مهندس")},
    {QString::fromUtf8("💂"), QString::fromUtf8("guard soldier نگهبان سرباز گارد")},
    {QString::fromUtf8("🕵️"), QString::fromUtf8("detective spy کارآگاه جاسوس")},
    {QString::fromUtf8("🧑‍⚕️"), QString::fromUtf8("health worker doctor nurse دکتر پزشک پرستار")},
    {QString::fromUtf8("🧑‍🌾"), QString::fromUtf8("farmer کشاورز باغبان")},
    {QString::fromUtf8("🧑‍🍳"), QString::fromUtf8("cook chef آشپز سرآشپز")},
    {QString::fromUtf8("🧑‍🎓"), QString::fromUtf8("student graduate دانشجو دانش آموز فارغ التحصیل")},
    {QString::fromUtf8("🧑‍🏫"), QString::fromUtf8("teacher معلم استاد آموزگار")},
    {QString::fromUtf8("🧑‍💻"), QString::fromUtf8("technologist programmer developer برنامه نویس کامپیوتر")},
    {QString::fromUtf8("🧑‍🔧"), QString::fromUtf8("mechanic تعمیرکار مکانیک")},
    {QString::fromUtf8("🧑‍🚒"), QString::fromUtf8("firefighter آتش نشان")},
    {QString::fromUtf8("🧑‍✈️"), QString::fromUtf8("pilot خلبان")},
    {QString::fromUtf8("🧑‍🚀"), QString::fromUtf8("astronaut space فضانورد")},
    {QString::fromUtf8("👰"), QString::fromUtf8("bride wedding veil عروس عروسی")},
    {QString::fromUtf8("🤵"), QString::fromUtf8("groom tuxedo wedding داماد کت شلوار")},
    {QString::fromUtf8("👸"), QString::fromUtf8("princess crown شاهزاده خانم پرنسس")},
    {QString::fromUtf8("🤴"), QString::fromUtf8("prince crown شاهزاده")},
    {QString::fromUtf8("🦸"), QString::fromUtf8("superhero hero قهرمان ابرقهرمان")},
    {QString::fromUtf8("🦹"), QString::fromUtf8("supervillain villain شرور تبهکار")},
    {QString::fromUtf8("🧙"), QString::fromUtf8("mage wizard magic جادوگر ساحر")},
    {QString::fromUtf8("🧚"), QString::fromUtf8("fairy پری فرشته")},
    {QString::fromUtf8("🧛"), QString::fromUtf8("vampire dracula خون آشام دراکولا")},
    {QString::fromUtf8("🧜"), QString::fromUtf8("merperson mermaid پری دریایی")},
    {QString::fromUtf8("🎅"), QString::fromUtf8("santa claus christmas بابانوئل کریسمس")},
    {QString::fromUtf8("🤶"), QString::fromUtf8("mrs claus christmas مامان نوئل کریسمس")},
    {QString::fromUtf8("🙍"), QString::fromUtf8("person frowning sad اخم ناراحت")},
    {QString::fromUtf8("🙎"), QString::fromUtf8("person pouting قهر دلخور")},
    {QString::fromUtf8("🙅"), QString::fromUtf8("no gesture refuse نه ممنوع رد")},
    {QString::fromUtf8("🙆"), QString::fromUtf8("ok gesture yes اوکی باشه قبول")},
    {QString::fromUtf8("💁"), QString::fromUtf8("person tipping hand sassy information اطلاعات راهنما")},
    {QString::fromUtf8("🙋"), QString::fromUtf8("raising hand question volunteer دست بالا سوال داوطلب")},
    {QString::fromUtf8("🙇"), QString::fromUtf8("bowing sorry respect تعظیم عذرخواهی احترام")},
    {QString::fromUtf8("🤦"), QString::fromUtf8("facepalm disbelief دست به پیشانی وای")},
    {QString::fromUtf8("🤷"), QString::fromUtf8("shrug dont know نمیدونم شانه بالا بی خیال")},
    {QString::fromUtf8("💆"), QString::fromUtf8("massage face relax ماساژ آرامش")},
    {QString::fromUtf8("💇"), QString::fromUtf8("haircut hairdresser کوتاهی مو آرایشگاه")},
    {QString::fromUtf8("🚶"), QString::fromUtf8("walking walk پیاده روی قدم زدن راه رفتن")},
    {QString::fromUtf8("🏃"), QString::fromUtf8("running run runner دویدن دو عجله")},
    {QString::fromUtf8("💃"), QString::fromUtf8("woman dancing dance رقص رقصیدن زن")},
    {QString::fromUtf8("🕺"), QString::fromUtf8("man dancing dance رقص رقصیدن مرد")},
    {QString::fromUtf8("🧍"), QString::fromUtf8("person standing ایستاده")},
    {QString::fromUtf8("🧎"), QString::fromUtf8("person kneeling زانو زدن")},
    {QString::fromUtf8("🏊"), QString::fromUtf8("swimming swimmer شنا شناگر")},
    {QString::fromUtf8("🚴"), QString::fromUtf8("biking cyclist دوچرخه سواری")},
    {QString::fromUtf8("🏋️"), QString::fromUtf8("weightlifting gym وزنه برداری باشگاه بدنسازی")},
    {QString::fromUtf8("🤸"), QString::fromUtf8("cartwheel gymnastics ژیمناستیک پشتک")},
    {QString::fromUtf8("🧘"), QString::fromUtf8("lotus yoga meditation یوگا مدیتیشن آرامش")},
    {QString::fromUtf8("🛀"), QString::fromUtf8("bath bathtub حمام وان")},
    {QString::fromUtf8("🛌"), QString::fromUtf8("sleeping bed خواب تخت خوابیدن")},
    {QString::fromUtf8("👫"), QString::fromUtf8("couple woman man holding hands زوج دست در دست")},
    {QString::fromUtf8("👬"), QString::fromUtf8("men holding hands دو مرد دست در دست")},
    {QString::fromUtf8("👭"), QString::fromUtf8("women holding hands دو زن دست در دست")},
    {QString::fromUtf8("💏"), QString::fromUtf8("kiss couple بوسه زوج عاشق")},
    {QString::fromUtf8("💑"), QString::fromUtf8("couple with heart love زوج عاشق قلب")},
    {QString::fromUtf8("👪"), QString::fromUtf8("family خانواده")},
    {QString::fromUtf8("🗣"), QString::fromUtf8("speaking head talk حرف زدن صحبت")},
    {QString::fromUtf8("👥"), QString::fromUtf8("busts silhouette people افراد مردم گروه")},
    {QString::fromUtf8("🫂"), QString::fromUtf8("people hugging hug بغل آغوش دلداری")},
    {QString::fromUtf8("👣"), QString::fromUtf8("footprints steps رد پا جای پا")},

    // ===== Clothing & Accessories =====
    {QString::fromUtf8("👓"), QString::fromUtf8("glasses eyeglasses عینک طبی")},
    {QString::fromUtf8("🕶"), QString::fromUtf8("sunglasses cool عینک آفتابی دودی")},
    {QString::fromUtf8("🧥"), QString::fromUtf8("coat jacket کت پالتو کاپشن")},
    {QString::fromUtf8("👔"), QString::fromUtf8("necktie shirt business کراوات پیراهن رسمی")},
    {QString::fromUtf8("👕"), QString::fromUtf8("tshirt shirt تیشرت پیراهن لباس")},
    {QString::fromUtf8("👖"), QString::fromUtf8("jeans pants trousers شلوار جین")},
    {QString::fromUtf8("🧣"), QString::fromUtf8("scarf شال گردن روسری")},
    {QString::fromUtf8("🧤"), QString::fromUtf8("gloves دستکش")},
    {QString::fromUtf8("🧦"), QString::fromUtf8("socks جوراب")},
    {QString::fromUtf8("👗"), QString::fromUtf8("dress پیراهن زنانه لباس")},
    {QString::fromUtf8("👙"), QString::fromUtf8("bikini swimsuit بیکینی مایو")},
    {QString::fromUtf8("👘"), QString::fromUtf8("kimono کیمونو")},
    {QString::fromUtf8("🩳"), QString::fromUtf8("shorts شلوارک")},
    {QString::fromUtf8("👚"), QString::fromUtf8("womans clothes blouse بلوز لباس زنانه")},
    {QString::fromUtf8("👛"), QString::fromUtf8("purse کیف پول زنانه")},
    {QString::fromUtf8("👜"), QString::fromUtf8("handbag کیف دستی زنانه")},
    {QString::fromUtf8("🎒"), QString::fromUtf8("backpack school bag کوله پشتی مدرسه")},
    {QString::fromUtf8("🧳"), QString::fromUtf8("luggage suitcase travel چمدان سفر")},
    {QString::fromUtf8("👞"), QString::fromUtf8("mans shoe کفش مردانه")},
    {QString::fromUtf8("👟"), QString::fromUtf8("running shoe sneaker کفش ورزشی کتونی")},
    {QString::fromUtf8("🥾"), QString::fromUtf8("hiking boot بوت کوهنوردی")},
    {QString::fromUtf8("👠"), QString::fromUtf8("high heel shoe کفش پاشنه بلند")},
    {QString::fromUtf8("👡"), QString::fromUtf8("womans sandal صندل زنانه")},
    {QString::fromUtf8("👑"), QString::fromUtf8("crown king queen تاج پادشاه ملکه سلطان")},
    {QString::fromUtf8("👒"), QString::fromUtf8("womans hat کلاه زنانه")},
    {QString::fromUtf8("🎩"), QString::fromUtf8("top hat magic کلاه شعبده مجیک")},
    {QString::fromUtf8("🧢"), QString::fromUtf8("billed cap baseball کلاه نقاب دار کپ")},
    {QString::fromUtf8("⛑"), QString::fromUtf8("rescue helmet کلاه ایمنی نجات")},
    {QString::fromUtf8("💄"), QString::fromUtf8("lipstick makeup رژ لب آرایش")},
    {QString::fromUtf8("💍"), QString::fromUtf8("ring diamond wedding حلقه انگشتر ازدواج نامزدی")},
    {QString::fromUtf8("🌂"), QString::fromUtf8("closed umbrella چتر بسته")},
    {QString::fromUtf8("☂️"), QString::fromUtf8("umbrella rain چتر باران")},

    // ===== Plants & Weather =====
    {QString::fromUtf8("💐"), QString::fromUtf8("bouquet flowers دسته گل")},
    {QString::fromUtf8("🌸"), QString::fromUtf8("cherry blossom flower spring شکوفه گیلاس بهار گل")},
    {QString::fromUtf8("💮"), QString::fromUtf8("white flower گل سفید")},
    {QString::fromUtf8("🌹"), QString::fromUtf8("rose flower love گل رز عشق")},
    {QString::fromUtf8("🥀"), QString::fromUtf8("wilted flower sad گل پژمرده خشک")},
    {QString::fromUtf8("🌺"), QString::fromUtf8("hibiscus flower گل ختمی")},
    {QString::fromUtf8("🌻"), QString::fromUtf8("sunflower گل آفتابگردان")},
    {QString::fromUtf8("🌼"), QString::fromUtf8("blossom daisy flower گل بابونه شکوفه")},
    {QString::fromUtf8("🌷"), QString::fromUtf8("tulip flower گل لاله")},
    {QString::fromUtf8("🌱"), QString::fromUtf8("seedling plant sprout جوانه نهال گیاه")},
    {QString::fromUtf8("🪴"), QString::fromUtf8("potted plant گلدان گیاه")},
    {QString::fromUtf8("🌲"), QString::fromUtf8("evergreen tree pine درخت کاج سرو")},
    {QString::fromUtf8("🌳"), QString::fromUtf8("deciduous tree درخت")},
    {QString::fromUtf8("🌴"), QString::fromUtf8("palm tree beach درخت نخل ساحل")},
    {QString::fromUtf8("🌵"), QString::fromUtf8("cactus desert کاکتوس بیابان")},
    {QString::fromUtf8("🌾"), QString::fromUtf8("sheaf of rice wheat گندم برنج خوشه")},
    {QString::fromUtf8("🌿"), QString::fromUtf8("herb leaf سبزی برگ گیاه")},
    {QString::fromUtf8("☘️"), QString::fromUtf8("shamrock clover شبدر")},
    {QString::fromUtf8("🍀"), QString::fromUtf8("four leaf clover luck شبدر چهاربرگ شانس")},
    {QString::fromUtf8("🍁"), QString::fromUtf8("maple leaf autumn fall برگ افرا پاییز")},
    {QString::fromUtf8("🍂"), QString::fromUtf8("fallen leaves autumn برگ ریزان پاییز")},
    {QString::fromUtf8("🍃"), QString::fromUtf8("leaf wind برگ باد سبز")},
    {QString::fromUtf8("🍄"), QString::fromUtf8("mushroom قارچ")},
    {QString::fromUtf8("☀️"), QString::fromUtf8("sun sunny خورشید آفتاب آفتابی")},
    {QString::fromUtf8("🌤"), QString::fromUtf8("sun behind small cloud آفتاب کمی ابری")},
    {QString::fromUtf8("⛅️"), QString::fromUtf8("sun behind cloud partly cloudy نیمه ابری آفتاب ابر")},
    {QString::fromUtf8("☁️"), QString::fromUtf8("cloud cloudy ابر ابری")},
    {QString::fromUtf8("🌧"), QString::fromUtf8("rain cloud rainy باران بارانی ابر")},
    {QString::fromUtf8("⛈"), QString::fromUtf8("thunderstorm lightning rain رعد و برق طوفان باران")},
    {QString::fromUtf8("🌩"), QString::fromUtf8("cloud with lightning صاعقه رعد")},
    {QString::fromUtf8("🌨"), QString::fromUtf8("cloud with snow snowy برف بارش ابر")},
    {QString::fromUtf8("⛄️"), QString::fromUtf8("snowman winter آدم برفی زمستان")},
    {QString::fromUtf8("☔️"), QString::fromUtf8("umbrella rain drops چتر باران")},
    {QString::fromUtf8("🌬"), QString::fromUtf8("wind face blowing باد وزیدن")},
    {QString::fromUtf8("🌪"), QString::fromUtf8("tornado storm گردباد طوفان")},
    {QString::fromUtf8("🌫"), QString::fromUtf8("fog مه")},
    {QString::fromUtf8("🌈"), QString::fromUtf8("rainbow رنگین کمان")},
    {QString::fromUtf8("🌊"), QString::fromUtf8("water wave sea ocean موج دریا اقیانوس")},
    {QString::fromUtf8("🌙"), QString::fromUtf8("crescent moon night ماه هلال شب")},
    {QString::fromUtf8("🌕"), QString::fromUtf8("full moon ماه کامل قرص ماه")},
    {QString::fromUtf8("🌑"), QString::fromUtf8("new moon dark ماه نو تاریک")},
    {QString::fromUtf8("🌍"), QString::fromUtf8("globe earth world کره زمین جهان دنیا")},
    {QString::fromUtf8("🪐"), QString::fromUtf8("ringed planet saturn سیاره زحل")},
    {QString::fromUtf8("☄️"), QString::fromUtf8("comet شهاب ستاره دنباله دار")},
    {QString::fromUtf8("🌋"), QString::fromUtf8("volcano آتشفشان")},
    {QString::fromUtf8("🏔"), QString::fromUtf8("snow capped mountain کوه برفی قله")},

    // ===== More Symbols =====
    {QString::fromUtf8("❓"), QString::fromUtf8("question mark علامت سوال پرسش")},
    {QString::fromUtf8("❗️"), QString::fromUtf8("exclamation mark علامت تعجب")},
    {QString::fromUtf8("💤"), QString::fromUtf8("zzz sleep خواب خوابیدن")},
    {QString::fromUtf8("💢"), QString::fromUtf8("anger symbol عصبانیت خشم")},
    {QString::fromUtf8("💬"), QString::fromUtf8("speech balloon chat حباب گفتگو پیام چت")},
    {QString::fromUtf8("💭"), QString::fromUtf8("thought balloon think حباب فکر خیال")},
    {QString::fromUtf8("♻️"), QString::fromUtf8("recycling symbol بازیافت")},
    {QString::fromUtf8("🔞"), QString::fromUtf8("no one under eighteen 18 زیر هجده ممنوع")},
    {QString::fromUtf8("🆗"), QString::fromUtf8("ok button اوکی باشه")},
    {QString::fromUtf8("🆕"), QString::fromUtf8("new button جدید نو")},
    {QString::fromUtf8("🆓"), QString::fromUtf8("free button رایگان مجانی")},
    {QString::fromUtf8("🔴"), QString::fromUtf8("red circle دایره قرمز")},
    {QString::fromUtf8("🟠"), QString::fromUtf8("orange circle دایره نارنجی")},
    {QString::fromUtf8("🟡"), QString::fromUtf8("yellow circle دایره زرد")},
    {QString::fromUtf8("🟢"), QString::fromUtf8("green circle دایره سبز")},
    {QString::fromUtf8("🔵"), QString::fromUtf8("blue circle دایره آبی")},
    {QString::fromUtf8("🟣"), QString::fromUtf8("purple circle دایره بنفش")},
    {QString::fromUtf8("⚫️"), QString::fromUtf8("black circle دایره مشکی سیاه")},
    {QString::fromUtf8("⚪️"), QString::fromUtf8("white circle دایره سفید")},
    {QString::fromUtf8("➕"), QString::fromUtf8("plus add جمع بعلاوه اضافه")},
    {QString::fromUtf8("➖"), QString::fromUtf8("minus subtract منها تفریق")},
    {QString::fromUtf8("➗"), QString::fromUtf8("divide division تقسیم")},
    {QString::fromUtf8("✖️"), QString::fromUtf8("multiply multiplication ضرب")},
    {QString::fromUtf8("♾"), QString::fromUtf8("infinity بی نهایت")},
    {QString::fromUtf8("💲"), QString::fromUtf8("dollar sign علامت دلار پول")},
    {QString::fromUtf8("🔔"), QString::fromUtf8("bell notification زنگ اعلان نوتیفیکیشن")},
    {QString::fromUtf8("🔕"), QString::fromUtf8("bell with slash mute بی صدا سایلنت زنگ خاموش")},
    {QString::fromUtf8("📢"), QString::fromUtf8("loudspeaker announcement بلندگو اعلامیه")},
    {QString::fromUtf8("📣"), QString::fromUtf8("megaphone shout بلندگو فریاد")},
    {QString::fromUtf8("🔍"), QString::fromUtf8("magnifying glass search ذره بین جستجو")},
    {QString::fromUtf8("🔎"), QString::fromUtf8("magnifying glass right search ذره بین جستجو")},
    {QString::fromUtf8("🔗"), QString::fromUtf8("link chain لینک پیوند زنجیر")},
    {QString::fromUtf8("🎵"), QString::fromUtf8("musical note music نت موسیقی آهنگ")},
    {QString::fromUtf8("🎶"), QString::fromUtf8("musical notes music نت ها موسیقی آهنگ")},
    {QString::fromUtf8("🔊"), QString::fromUtf8("speaker high volume loud بلندگو صدای بلند")},
    {QString::fromUtf8("🔇"), QString::fromUtf8("muted speaker silent بی صدا قطع صدا")},
    {QString::fromUtf8("📴"), QString::fromUtf8("mobile phone off گوشی خاموش")},
    {QString::fromUtf8("✔️"), QString::fromUtf8("check mark تیک تایید")},
    {QString::fromUtf8("☑️"), QString::fromUtf8("check box with check چک باکس تیک")},
    {QString::fromUtf8("⬆️"), QString::fromUtf8("up arrow فلش بالا")},
    {QString::fromUtf8("⬇️"), QString::fromUtf8("down arrow فلش پایین")},
    {QString::fromUtf8("⬅️"), QString::fromUtf8("left arrow فلش چپ")},
    {QString::fromUtf8("➡️"), QString::fromUtf8("right arrow فلش راست")},
    {QString::fromUtf8("🔄"), QString::fromUtf8("counterclockwise arrows refresh بروزرسانی چرخش تازه سازی")},
    {QString::fromUtf8("🕐"), QString::fromUtf8("one oclock clock time ساعت یک زمان")},
    {QString::fromUtf8("⏰"), QString::fromUtf8("alarm clock ساعت زنگ دار زنگ بیدارباش")},
    {QString::fromUtf8("🚹"), QString::fromUtf8("mens room restroom دستشویی مردانه")},
    {QString::fromUtf8("🚺"), QString::fromUtf8("womens room restroom دستشویی زنانه")},
    {QString::fromUtf8("♿️"), QString::fromUtf8("wheelchair accessible ویلچر معلول")},
    {QString::fromUtf8("🚻"), QString::fromUtf8("restroom toilet سرویس بهداشتی دستشویی")},

    // ===== Celebration & Misc =====
    {QString::fromUtf8("🎊"), QString::fromUtf8("confetti ball celebration کاغذ رنگی جشن")},
    {QString::fromUtf8("🎃"), QString::fromUtf8("jack o lantern halloween pumpkin کدو هالووین")},
    {QString::fromUtf8("🎄"), QString::fromUtf8("christmas tree درخت کریسمس")},
    {QString::fromUtf8("🧧"), QString::fromUtf8("red envelope gift money پاکت قرمز عیدی")},
    {QString::fromUtf8("🪅"), QString::fromUtf8("pinata party پیناتا جشن")},
    {QString::fromUtf8("🎐"), QString::fromUtf8("wind chime زنگ بادی")},
    {QString::fromUtf8("🪔"), QString::fromUtf8("diya lamp oil چراغ نفتی پیه سوز")},
    {QString::fromUtf8("🧵"), QString::fromUtf8("thread sewing نخ خیاطی")},
    {QString::fromUtf8("🧶"), QString::fromUtf8("yarn knitting کاموا بافتنی")},
    {QString::fromUtf8("📚"), QString::fromUtf8("books study library کتاب مطالعه کتابخانه درس")},
    {QString::fromUtf8("📖"), QString::fromUtf8("open book read کتاب باز خواندن")},
    {QString::fromUtf8("✏️"), QString::fromUtf8("pencil write مداد نوشتن")},
    {QString::fromUtf8("🖊"), QString::fromUtf8("pen ballpoint خودکار قلم")},
    {QString::fromUtf8("✂️"), QString::fromUtf8("scissors cut قیچی بریدن")},
    {QString::fromUtf8("📌"), QString::fromUtf8("pushpin pin پونز سنجاق پین")},
    {QString::fromUtf8("📎"), QString::fromUtf8("paperclip گیره کاغذ")},
    {QString::fromUtf8("📏"), QString::fromUtf8("ruler straight خط کش")},
    {QString::fromUtf8("🔭"), QString::fromUtf8("telescope stars تلسکوپ ستاره")},
    {QString::fromUtf8("🔬"), QString::fromUtf8("microscope science میکروسکوپ علم آزمایش")},
    {QString::fromUtf8("🧪"), QString::fromUtf8("test tube experiment lab لوله آزمایش آزمایشگاه")},
    {QString::fromUtf8("🧬"), QString::fromUtf8("dna gene ژن دی ان ای ژنتیک")},
    {QString::fromUtf8("🌡"), QString::fromUtf8("thermometer temperature دماسنج دما")},

    // ===== Moon Phases =====
    {QString::fromUtf8("🌒"), QString::fromUtf8("waxing crescent moon هلال ماه نو")},
    {QString::fromUtf8("🌓"), QString::fromUtf8("first quarter moon نیمه ماه ربع اول")},
    {QString::fromUtf8("🌔"), QString::fromUtf8("waxing gibbous moon ماه محدب")},
    {QString::fromUtf8("🌖"), QString::fromUtf8("waning gibbous moon ماه در حال کاهش")},
    {QString::fromUtf8("🌗"), QString::fromUtf8("last quarter moon نیمه ماه ربع آخر")},
    {QString::fromUtf8("🌘"), QString::fromUtf8("waning crescent moon هلال ماه کاهنده")},
    {QString::fromUtf8("🌚"), QString::fromUtf8("new moon face dark ماه صورت تاریک")},
    {QString::fromUtf8("🌝"), QString::fromUtf8("full moon face ماه کامل صورت")},
    {QString::fromUtf8("🌛"), QString::fromUtf8("first quarter moon face ماه صورت هلال چپ")},
    {QString::fromUtf8("🌜"), QString::fromUtf8("last quarter moon face ماه صورت هلال راست")},
    {QString::fromUtf8("🌞"), QString::fromUtf8("sun with face خورشید صورت آفتاب")},

    // ===== Clocks =====
    {QString::fromUtf8("🕑"), QString::fromUtf8("two oclock clock ساعت دو")},
    {QString::fromUtf8("🕒"), QString::fromUtf8("three oclock clock ساعت سه")},
    {QString::fromUtf8("🕓"), QString::fromUtf8("four oclock clock ساعت چهار")},
    {QString::fromUtf8("🕔"), QString::fromUtf8("five oclock clock ساعت پنج")},
    {QString::fromUtf8("🕕"), QString::fromUtf8("six oclock clock ساعت شش")},
    {QString::fromUtf8("🕖"), QString::fromUtf8("seven oclock clock ساعت هفت")},
    {QString::fromUtf8("🕗"), QString::fromUtf8("eight oclock clock ساعت هشت")},
    {QString::fromUtf8("🕘"), QString::fromUtf8("nine oclock clock ساعت نه")},
    {QString::fromUtf8("🕙"), QString::fromUtf8("ten oclock clock ساعت ده")},
    {QString::fromUtf8("🕚"), QString::fromUtf8("eleven oclock clock ساعت یازده")},
    {QString::fromUtf8("🕛"), QString::fromUtf8("twelve oclock clock ساعت دوازده ظهر نیمه شب")},

    // ===== Flags =====
    {QString::fromUtf8("🏁"), QString::fromUtf8("chequered flag race finish پرچم شطرنجی مسابقه پایان")},
    {QString::fromUtf8("🚩"), QString::fromUtf8("triangular flag پرچم مثلثی علامت")},
    {QString::fromUtf8("🏴"), QString::fromUtf8("black flag پرچم سیاه مشکی")},
    {QString::fromUtf8("🏳️"), QString::fromUtf8("white flag surrender پرچم سفید تسلیم")},
    {QString::fromUtf8("🏳️‍🌈"), QString::fromUtf8("rainbow flag pride پرچم رنگین کمان")},
    {QString::fromUtf8("🏴‍☠️"), QString::fromUtf8("pirate flag jolly roger پرچم دزد دریایی")},
    {QString::fromUtf8("�🇳"), QString::fromUtf8("united nations flag un سازمان ملل پرچم")},
    {QString::fromUtf8("🇪🇺"), QString::fromUtf8("european union flag eu اتحادیه اروپا پرچم")},
    {QString::fromUtf8("🇦🇫"), QString::fromUtf8("afghanistan flag افغانستان پرچم")},
    {QString::fromUtf8("🇦🇱"), QString::fromUtf8("albania flag آلبانی پرچم")},
    {QString::fromUtf8("🇩🇿"), QString::fromUtf8("algeria flag الجزایر پرچم")},
    {QString::fromUtf8("🇦🇩"), QString::fromUtf8("andorra flag آندورا پرچم")},
    {QString::fromUtf8("🇦🇴"), QString::fromUtf8("angola flag آنگولا پرچم")},
    {QString::fromUtf8("🇦🇬"), QString::fromUtf8("antigua barbuda flag آنتیگوا باربودا پرچم")},
    {QString::fromUtf8("🇦🇷"), QString::fromUtf8("argentina flag آرژانتین پرچم")},
    {QString::fromUtf8("🇦🇲"), QString::fromUtf8("armenia flag ارمنستان پرچم")},
    {QString::fromUtf8("🇦🇺"), QString::fromUtf8("australia flag استرالیا پرچم")},
    {QString::fromUtf8("🇦🇹"), QString::fromUtf8("austria flag اتریش پرچم")},
    {QString::fromUtf8("🇦🇿"), QString::fromUtf8("azerbaijan flag آذربایجان پرچم")},
    {QString::fromUtf8("🇧🇸"), QString::fromUtf8("bahamas flag باهاما پرچم")},
    {QString::fromUtf8("🇧🇭"), QString::fromUtf8("bahrain flag بحرین پرچم")},
    {QString::fromUtf8("🇧🇩"), QString::fromUtf8("bangladesh flag بنگلادش پرچم")},
    {QString::fromUtf8("🇧🇧"), QString::fromUtf8("barbados flag باربادوس پرچم")},
    {QString::fromUtf8("🇧🇾"), QString::fromUtf8("belarus flag بلاروس پرچم")},
    {QString::fromUtf8("🇧🇪"), QString::fromUtf8("belgium flag بلژیک پرچم")},
    {QString::fromUtf8("🇧🇿"), QString::fromUtf8("belize flag بلیز پرچم")},
    {QString::fromUtf8("🇧🇯"), QString::fromUtf8("benin flag بنین پرچم")},
    {QString::fromUtf8("🇧🇹"), QString::fromUtf8("bhutan flag بوتان پرچم")},
    {QString::fromUtf8("🇧🇴"), QString::fromUtf8("bolivia flag بولیوی پرچم")},
    {QString::fromUtf8("🇧🇦"), QString::fromUtf8("bosnia herzegovina flag بوسنی هرزگوین پرچم")},
    {QString::fromUtf8("🇧🇼"), QString::fromUtf8("botswana flag بوتسوانا پرچم")},
    {QString::fromUtf8("🇧🇷"), QString::fromUtf8("brazil flag برزیل پرچم")},
    {QString::fromUtf8("🇧🇳"), QString::fromUtf8("brunei flag برونئی پرچم")},
    {QString::fromUtf8("🇧🇬"), QString::fromUtf8("bulgaria flag بلغارستان پرچم")},
    {QString::fromUtf8("🇧🇫"), QString::fromUtf8("burkina faso flag بورکینافاسو پرچم")},
    {QString::fromUtf8("🇧🇮"), QString::fromUtf8("burundi flag بوروندی پرچم")},
    {QString::fromUtf8("🇨🇻"), QString::fromUtf8("cabo verde flag کیپ ورد پرچم")},
    {QString::fromUtf8("🇰🇭"), QString::fromUtf8("cambodia flag کامبوج پرچم")},
    {QString::fromUtf8("🇨🇲"), QString::fromUtf8("cameroon flag کامرون پرچم")},
    {QString::fromUtf8("🇨🇦"), QString::fromUtf8("canada flag کانادا پرچم")},
    {QString::fromUtf8("🇨🇫"), QString::fromUtf8("central african republic flag آفریقای مرکزی پرچم")},
    {QString::fromUtf8("🇹🇩"), QString::fromUtf8("chad flag چاد پرچم")},
    {QString::fromUtf8("🇨🇱"), QString::fromUtf8("chile flag شیلی پرچم")},
    {QString::fromUtf8("🇨🇳"), QString::fromUtf8("china flag چین پرچم")},
    {QString::fromUtf8("🇨🇴"), QString::fromUtf8("colombia flag کلمبیا پرچم")},
    {QString::fromUtf8("🇰🇲"), QString::fromUtf8("comoros flag کومور پرچم")},
    {QString::fromUtf8("🇨🇬"), QString::fromUtf8("congo flag کنگو پرچم")},
    {QString::fromUtf8("🇨🇩"), QString::fromUtf8("congo democratic republic flag جمهوری دموکراتیک کنگو پرچم")},
    {QString::fromUtf8("🇨🇷"), QString::fromUtf8("costa rica flag کاستاریکا پرچم")},
    {QString::fromUtf8("🇭🇷"), QString::fromUtf8("croatia flag کرواسی پرچم")},
    {QString::fromUtf8("🇨🇺"), QString::fromUtf8("cuba flag کوبا پرچم")},
    {QString::fromUtf8("🇨🇾"), QString::fromUtf8("cyprus flag قبرس پرچم")},
    {QString::fromUtf8("🇨🇿"), QString::fromUtf8("czechia flag چک پرچم")},
    {QString::fromUtf8("🇩🇰"), QString::fromUtf8("denmark flag دانمارک پرچم")},
    {QString::fromUtf8("🇩🇯"), QString::fromUtf8("djibouti flag جیبوتی پرچم")},
    {QString::fromUtf8("🇩🇲"), QString::fromUtf8("dominica flag دومینیکا پرچم")},
    {QString::fromUtf8("🇩🇴"), QString::fromUtf8("dominican republic flag جمهوری دومینیکن پرچم")},
    {QString::fromUtf8("🇪🇨"), QString::fromUtf8("ecuador flag اکوادور پرچم")},
    {QString::fromUtf8("🇪🇬"), QString::fromUtf8("egypt flag مصر پرچم")},
    {QString::fromUtf8("🇸🇻"), QString::fromUtf8("el salvador flag السالوادور پرچم")},
    {QString::fromUtf8("🇬🇶"), QString::fromUtf8("equatorial guinea flag گینه استوایی پرچم")},
    {QString::fromUtf8("🇪🇷"), QString::fromUtf8("eritrea flag اریتره پرچم")},
    {QString::fromUtf8("🇪🇪"), QString::fromUtf8("estonia flag استونی پرچم")},
    {QString::fromUtf8("🇸🇿"), QString::fromUtf8("eswatini flag اسواتینی پرچم")},
    {QString::fromUtf8("🇪🇹"), QString::fromUtf8("ethiopia flag اثیوپی پرچم")},
    {QString::fromUtf8("🇫🇯"), QString::fromUtf8("fiji flag فیجی پرچم")},
    {QString::fromUtf8("🇫🇮"), QString::fromUtf8("finland flag فنلاند پرچم")},
    {QString::fromUtf8("🇫🇷"), QString::fromUtf8("france flag فرانسه پرچم")},
    {QString::fromUtf8("🇬🇦"), QString::fromUtf8("gabon flag گابن پرچم")},
    {QString::fromUtf8("🇬🇲"), QString::fromUtf8("gambia flag گامبیا پرچم")},
    {QString::fromUtf8("🇬🇪"), QString::fromUtf8("georgia flag گرجستان پرچم")},
    {QString::fromUtf8("🇩🇪"), QString::fromUtf8("germany flag آلمان پرچم")},
    {QString::fromUtf8("🇬🇭"), QString::fromUtf8("ghana flag غنا پرچم")},
    {QString::fromUtf8("🇬🇷"), QString::fromUtf8("greece flag یونان پرچم")},
    {QString::fromUtf8("🇬🇩"), QString::fromUtf8("grenada flag گرنادا پرچم")},
    {QString::fromUtf8("🇬🇹"), QString::fromUtf8("guatemala flag گواتمالا پرچم")},
    {QString::fromUtf8("🇬🇳"), QString::fromUtf8("guinea flag گینه پرچم")},
    {QString::fromUtf8("🇬🇼"), QString::fromUtf8("guinea bissau flag گینه بیسائو پرچم")},
    {QString::fromUtf8("🇬🇾"), QString::fromUtf8("guyana flag گویان پرچم")},
    {QString::fromUtf8("🇭🇹"), QString::fromUtf8("haiti flag هائیتی پرچم")},
    {QString::fromUtf8("🇭🇳"), QString::fromUtf8("honduras flag هندوراس پرچم")},
    {QString::fromUtf8("🇭🇺"), QString::fromUtf8("hungary flag مجارستان پرچم")},
    {QString::fromUtf8("🇮🇸"), QString::fromUtf8("iceland flag ایسلند پرچم")},
    {QString::fromUtf8("🇮🇳"), QString::fromUtf8("india flag هند پرچم")},
    {QString::fromUtf8("🇮🇩"), QString::fromUtf8("indonesia flag اندونزی پرچم")},
    {QString::fromUtf8("🇮🇷"), QString::fromUtf8("iran flag ایران پرچم")},
    {QString::fromUtf8("🇮🇶"), QString::fromUtf8("iraq flag عراق پرچم")},
    {QString::fromUtf8("🇮🇪"), QString::fromUtf8("ireland flag ایرلند پرچم")},
    {QString::fromUtf8("🇮🇱"), QString::fromUtf8("israel flag اسرائیل پرچم")},
    {QString::fromUtf8("🇮🇹"), QString::fromUtf8("italy flag ایتالیا پرچم")},
    {QString::fromUtf8("🇯🇲"), QString::fromUtf8("jamaica flag جامائیکا پرچم")},
    {QString::fromUtf8("🇯🇵"), QString::fromUtf8("japan flag ژاپن پرچم")},
    {QString::fromUtf8("🇯🇴"), QString::fromUtf8("jordan flag اردن پرچم")},
    {QString::fromUtf8("🇰🇿"), QString::fromUtf8("kazakhstan flag قزاقستان پرچم")},
    {QString::fromUtf8("🇰🇪"), QString::fromUtf8("kenya flag کنیا پرچم")},
    {QString::fromUtf8("🇰🇮"), QString::fromUtf8("kiribati flag کیریباتی پرچم")},
    {QString::fromUtf8("🇰🇵"), QString::fromUtf8("north korea flag کره شمالی پرچم")},
    {QString::fromUtf8("🇰🇷"), QString::fromUtf8("south korea flag کره جنوبی پرچم")},
    {QString::fromUtf8("🇰🇼"), QString::fromUtf8("kuwait flag کویت پرچم")},
    {QString::fromUtf8("🇰🇬"), QString::fromUtf8("kyrgyzstan flag قرقیزستان پرچم")},
    {QString::fromUtf8("🇱🇦"), QString::fromUtf8("laos flag لائوس پرچم")},
    {QString::fromUtf8("🇱🇻"), QString::fromUtf8("latvia flag لتونی پرچم")},
    {QString::fromUtf8("🇱🇧"), QString::fromUtf8("lebanon flag لبنان پرچم")},
    {QString::fromUtf8("🇱🇸"), QString::fromUtf8("lesotho flag لسوتو پرچم")},
    {QString::fromUtf8("🇱🇷"), QString::fromUtf8("liberia flag لیبریا پرچم")},
    {QString::fromUtf8("🇱🇾"), QString::fromUtf8("libya flag لیبی پرچم")},
    {QString::fromUtf8("🇱🇮"), QString::fromUtf8("liechtenstein flag لیختن اشتاین پرچم")},
    {QString::fromUtf8("🇱🇹"), QString::fromUtf8("lithuania flag لیتوانی پرچم")},
    {QString::fromUtf8("🇱🇺"), QString::fromUtf8("luxembourg flag لوکزامبورگ پرچم")},
    {QString::fromUtf8("🇲🇬"), QString::fromUtf8("madagascar flag ماداگاسکار پرچم")},
    {QString::fromUtf8("🇲🇼"), QString::fromUtf8("malawi flag مالاوی پرچم")},
    {QString::fromUtf8("🇲🇾"), QString::fromUtf8("malaysia flag مالزی پرچم")},
    {QString::fromUtf8("🇲🇻"), QString::fromUtf8("maldives flag مالدیو پرچم")},
    {QString::fromUtf8("🇲🇱"), QString::fromUtf8("mali flag مالی پرچم")},
    {QString::fromUtf8("🇲🇹"), QString::fromUtf8("malta flag مالت پرچم")},
    {QString::fromUtf8("🇲🇭"), QString::fromUtf8("marshall islands flag جزایر مارشال پرچم")},
    {QString::fromUtf8("🇲🇷"), QString::fromUtf8("mauritania flag موریتانی پرچم")},
    {QString::fromUtf8("🇲🇺"), QString::fromUtf8("mauritius flag موریس پرچم")},
    {QString::fromUtf8("🇲🇽"), QString::fromUtf8("mexico flag مکزیک پرچم")},
    {QString::fromUtf8("🇫🇲"), QString::fromUtf8("micronesia flag میکرونزی پرچم")},
    {QString::fromUtf8("🇲🇩"), QString::fromUtf8("moldova flag مولداوی پرچم")},
    {QString::fromUtf8("🇲🇨"), QString::fromUtf8("monaco flag موناکو پرچم")},
    {QString::fromUtf8("🇲🇳"), QString::fromUtf8("mongolia flag مغولستان پرچم")},
    {QString::fromUtf8("🇲🇪"), QString::fromUtf8("montenegro flag مونته نگرو پرچم")},
    {QString::fromUtf8("🇲🇦"), QString::fromUtf8("morocco flag مراکش پرچم")},
    {QString::fromUtf8("🇲🇿"), QString::fromUtf8("mozambique flag موزامبیک پرچم")},
    {QString::fromUtf8("🇲🇲"), QString::fromUtf8("myanmar burma flag میانمار برمه پرچم")},
    {QString::fromUtf8("🇳🇦"), QString::fromUtf8("namibia flag نامیبیا پرچم")},
    {QString::fromUtf8("🇳🇷"), QString::fromUtf8("nauru flag ناورو پرچم")},
    {QString::fromUtf8("🇳🇵"), QString::fromUtf8("nepal flag نپال پرچم")},
    {QString::fromUtf8("🇳🇱"), QString::fromUtf8("netherlands flag هلند پرچم")},
    {QString::fromUtf8("🇳🇿"), QString::fromUtf8("new zealand flag نیوزیلند پرچم")},
    {QString::fromUtf8("🇳🇮"), QString::fromUtf8("nicaragua flag نیکاراگوئه پرچم")},
    {QString::fromUtf8("🇳🇪"), QString::fromUtf8("niger flag نیجر پرچم")},
    {QString::fromUtf8("🇳🇬"), QString::fromUtf8("nigeria flag نیجریه پرچم")},
    {QString::fromUtf8("🇲🇰"), QString::fromUtf8("north macedonia flag مقدونیه شمالی پرچم")},
    {QString::fromUtf8("🇳🇴"), QString::fromUtf8("norway flag نروژ پرچم")},
    {QString::fromUtf8("🇴🇲"), QString::fromUtf8("oman flag عمان پرچم")},
    {QString::fromUtf8("🇵🇰"), QString::fromUtf8("pakistan flag پاکستان پرچم")},
    {QString::fromUtf8("🇵🇼"), QString::fromUtf8("palau flag پالائو پرچم")},
    {QString::fromUtf8("🇵🇸"), QString::fromUtf8("palestine flag فلسطین پرچم")},
    {QString::fromUtf8("🇵🇦"), QString::fromUtf8("panama flag پاناما پرچم")},
    {QString::fromUtf8("🇵🇬"), QString::fromUtf8("papua new guinea flag پاپوآ گینه نو پرچم")},
    {QString::fromUtf8("🇵🇾"), QString::fromUtf8("paraguay flag پاراگوئه پرچم")},
    {QString::fromUtf8("🇵🇪"), QString::fromUtf8("peru flag پرو پرچم")},
    {QString::fromUtf8("🇵🇭"), QString::fromUtf8("philippines flag فیلیپین پرچم")},
    {QString::fromUtf8("🇵🇱"), QString::fromUtf8("poland flag لهستان پرچم")},
    {QString::fromUtf8("🇵🇹"), QString::fromUtf8("portugal flag پرتغال پرچم")},
    {QString::fromUtf8("🇶🇦"), QString::fromUtf8("qatar flag قطر پرچم")},
    {QString::fromUtf8("🇷🇴"), QString::fromUtf8("romania flag رومانی پرچم")},
    {QString::fromUtf8("🇷🇺"), QString::fromUtf8("russia flag روسیه پرچم")},
    {QString::fromUtf8("🇷🇼"), QString::fromUtf8("rwanda flag رواندا پرچم")},
    {QString::fromUtf8("🇰🇳"), QString::fromUtf8("saint kitts nevis flag سنت کیتس نویس پرچم")},
    {QString::fromUtf8("🇱🇨"), QString::fromUtf8("saint lucia flag سنت لوسیا پرچم")},
    {QString::fromUtf8("🇻🇨"), QString::fromUtf8("saint vincent grenadines flag سنت وینسنت گرنادین ها پرچم")},
    {QString::fromUtf8("🇼🇸"), QString::fromUtf8("samoa flag ساموآ پرچم")},
    {QString::fromUtf8("🇸🇲"), QString::fromUtf8("san marino flag سان مارینو پرچم")},
    {QString::fromUtf8("🇸🇹"), QString::fromUtf8("sao tome principe flag سائوتومه پرنسیپ پرچم")},
    {QString::fromUtf8("🇸🇦"), QString::fromUtf8("saudi arabia flag عربستان سعودی پرچم")},
    {QString::fromUtf8("🇸🇳"), QString::fromUtf8("senegal flag سنگال پرچم")},
    {QString::fromUtf8("🇷🇸"), QString::fromUtf8("serbia flag صربستان پرچم")},
    {QString::fromUtf8("🇸🇨"), QString::fromUtf8("seychelles flag سیشل پرچم")},
    {QString::fromUtf8("🇸🇱"), QString::fromUtf8("sierra leone flag سیرالئون پرچم")},
    {QString::fromUtf8("🇸🇬"), QString::fromUtf8("singapore flag سنگاپور پرچم")},
    {QString::fromUtf8("🇸🇰"), QString::fromUtf8("slovakia flag اسلواکی پرچم")},
    {QString::fromUtf8("🇸🇮"), QString::fromUtf8("slovenia flag اسلوونی پرچم")},
    {QString::fromUtf8("🇸🇧"), QString::fromUtf8("solomon islands flag جزایر سلیمان پرچم")},
    {QString::fromUtf8("🇸🇴"), QString::fromUtf8("somalia flag سومالی پرچم")},
    {QString::fromUtf8("🇿🇦"), QString::fromUtf8("south africa flag آفریقای جنوبی پرچم")},
    {QString::fromUtf8("🇸🇸"), QString::fromUtf8("south sudan flag سودان جنوبی پرچم")},
    {QString::fromUtf8("🇪🇸"), QString::fromUtf8("spain flag اسپانیا پرچم")},
    {QString::fromUtf8("🇱🇰"), QString::fromUtf8("sri lanka flag سریلانکا پرچم")},
    {QString::fromUtf8("🇸🇩"), QString::fromUtf8("sudan flag سودان پرچم")},
    {QString::fromUtf8("🇸🇷"), QString::fromUtf8("suriname flag سورینام پرچم")},
    {QString::fromUtf8("🇸🇪"), QString::fromUtf8("sweden flag سوئد پرچم")},
    {QString::fromUtf8("🇨🇭"), QString::fromUtf8("switzerland flag سوئیس پرچم")},
    {QString::fromUtf8("🇸🇾"), QString::fromUtf8("syria flag سوریه پرچم")},
    {QString::fromUtf8("🇹🇼"), QString::fromUtf8("taiwan flag تایوان پرچم")},
    {QString::fromUtf8("🇹🇯"), QString::fromUtf8("tajikistan flag تاجیکستان پرچم")},
    {QString::fromUtf8("🇹🇿"), QString::fromUtf8("tanzania flag تانزانیا پرچم")},
    {QString::fromUtf8("🇹🇭"), QString::fromUtf8("thailand flag تایلند پرچم")},
    {QString::fromUtf8("🇹🇱"), QString::fromUtf8("timor leste flag تیمور شرقی پرچم")},
    {QString::fromUtf8("🇹🇬"), QString::fromUtf8("togo flag توگو پرچم")},
    {QString::fromUtf8("🇹🇴"), QString::fromUtf8("tonga flag تونگا پرچم")},
    {QString::fromUtf8("🇹🇹"), QString::fromUtf8("trinidad tobago flag ترینیداد توباگو پرچم")},
    {QString::fromUtf8("🇹🇳"), QString::fromUtf8("tunisia flag تونس پرچم")},
    {QString::fromUtf8("🇹🇷"), QString::fromUtf8("turkey flag ترکیه پرچم")},
    {QString::fromUtf8("🇹🇲"), QString::fromUtf8("turkmenistan flag ترکمنستان پرچم")},
    {QString::fromUtf8("🇹🇻"), QString::fromUtf8("tuvalu flag تووالو پرچم")},
    {QString::fromUtf8("🇺🇬"), QString::fromUtf8("uganda flag اوگاندا پرچم")},
    {QString::fromUtf8("🇺🇦"), QString::fromUtf8("ukraine flag اوکراین پرچم")},
    {QString::fromUtf8("🇦🇪"), QString::fromUtf8("uae united arab emirates flag امارات پرچم")},
    {QString::fromUtf8("🇬🇧"), QString::fromUtf8("uk united kingdom britain england flag بریتانیا انگلیس انگلستان پرچم")},
    {QString::fromUtf8("🇺🇸"), QString::fromUtf8("usa united states america flag آمریکا ایالات متحده پرچم")},
    {QString::fromUtf8("🇺🇾"), QString::fromUtf8("uruguay flag اروگوئه پرچم")},
    {QString::fromUtf8("🇺🇿"), QString::fromUtf8("uzbekistan flag ازبکستان پرچم")},
    {QString::fromUtf8("🇻🇺"), QString::fromUtf8("vanuatu flag وانواتو پرچم")},
    {QString::fromUtf8("🇻🇦"), QString::fromUtf8("vatican city flag واتیکان پرچم")},
    {QString::fromUtf8("🇻🇪"), QString::fromUtf8("venezuela flag ونزوئلا پرچم")},
    {QString::fromUtf8("🇻🇳"), QString::fromUtf8("vietnam flag ویتنام پرچم")},
    {QString::fromUtf8("🇾🇪"), QString::fromUtf8("yemen flag یمن پرچم")},
    {QString::fromUtf8("🇿🇲"), QString::fromUtf8("zambia flag زامبیا پرچم")},
    {QString::fromUtf8("🇿🇼"), QString::fromUtf8("zimbabwe flag زیمبابوه پرچم")},

    // ===== Extra Symbols & Signs =====
    {QString::fromUtf8("‼️"), QString::fromUtf8("double exclamation دو علامت تعجب مهم")},
    {QString::fromUtf8("⁉️"), QString::fromUtf8("exclamation question تعجب سوال")},
    {QString::fromUtf8("💥"), QString::fromUtf8("collision boom explosion انفجار بوم برخورد")},
    {QString::fromUtf8("🆒"), QString::fromUtf8("cool button باحال")},
    {QString::fromUtf8("🆙"), QString::fromUtf8("up button بالا آپ")},
    {QString::fromUtf8("🔝"), QString::fromUtf8("top arrow بالا برترین")},
    {QString::fromUtf8("🔙"), QString::fromUtf8("back arrow برگشت عقب")},
    {QString::fromUtf8("🔜"), QString::fromUtf8("soon arrow به زودی")},
    {QString::fromUtf8("©️"), QString::fromUtf8("copyright کپی رایت حق نشر")},
    {QString::fromUtf8("®️"), QString::fromUtf8("registered ثبت شده علامت تجاری")},
    {QString::fromUtf8("™️"), QString::fromUtf8("trademark علامت تجاری برند")},
    {QString::fromUtf8("〽️"), QString::fromUtf8("part alternation mark علامت")},
    {QString::fromUtf8("🔰"), QString::fromUtf8("beginner symbol تازه کار مبتدی")},
    {QString::fromUtf8("⭕️"), QString::fromUtf8("hollow red circle دایره قرمز درست")},
    {QString::fromUtf8("〰️"), QString::fromUtf8("wavy dash خط موجی")},
    {QString::fromUtf8("✳️"), QString::fromUtf8("eight spoked asterisk ستاره")},
    {QString::fromUtf8("❇️"), QString::fromUtf8("sparkle ستاره درخشش")},
    {QString::fromUtf8("💠"), QString::fromUtf8("diamond shape الماس نقش")},
    {QString::fromUtf8("🔱"), QString::fromUtf8("trident emblem سه شاخه نشان")},
    {QString::fromUtf8("⚜️"), QString::fromUtf8("fleur de lis نشان زنبق")},
    {QString::fromUtf8("🕎"), QString::fromUtf8("menorah judaism چراغدان یهودیت")},
    {QString::fromUtf8("🔯"), QString::fromUtf8("six pointed star ستاره شش پر")},
    {QString::fromUtf8("☸️"), QString::fromUtf8("dharma wheel چرخ دارما بودیسم")},
    {QString::fromUtf8("✡️"), QString::fromUtf8("star of david ستاره داوود یهودیت")},
    {QString::fromUtf8("🕉️"), QString::fromUtf8("om hindu اوم هندو")},
    };
}
